import { LoadedSchema } from './schema-loader';
import { resolveRef, isCommonEnum, getCommonBaseType } from './schema-loader';
import { resolveFromRoot, writeFile, logger, toSnakeCase } from './utils';
import path from 'path';

/** Rust reserved words that cannot be used as field names without r# prefix */
const RUST_RESERVED_WORDS = new Set([
  'type', 'async', 'await', 'break', 'const', 'continue', 'crate', 'dyn',
  'else', 'enum', 'extern', 'fn', 'for', 'if', 'impl', 'in', 'let',
  'loop', 'match', 'mod', 'move', 'mut', 'pub', 'ref', 'return',
  'self', 'Self', 'static', 'struct', 'super', 'trait', 'unsafe', 'use',
  'where', 'while', 'yield',
]);

/**
 * Generate Rust types from schemas.
 */
export function generateRustTypes(schemas: LoadedSchema[]): void {
  const outputDir = resolveFromRoot('crates', 'nexus-contracts', 'src', 'generated');
  logger.info(`Generating Rust types to: ${outputDir}`);

  // Filter schemas that need struct generation
  const structSchemas = schemas.filter(s => !s.isDefinitionsOnly);

  // Generate common types module first
  generateRustCommonTypes(outputDir);

  // Generate individual type files
  for (const schema of structSchemas) {
    generateRustTypeFile(schema, outputDir);
  }

  // Generate mod.rs with module declarations
  generateRustMod(structSchemas, outputDir);

  logger.success(`Generated Rust types for ${structSchemas.length} schema(s) (+ common types)`);
}

/**
 * Generate mod.rs with module declarations and re-exports.
 */
function generateRustMod(schemas: LoadedSchema[], outputDir: string): void {
  const modules: string[] = ['pub mod common_types;'];

  for (const schema of schemas) {
    const moduleName = toSnakeCase(schema.typeName);
    modules.push(`pub mod ${moduleName};`);
  }

  const content = `//! Nexus Wire Contracts - Generated Rust Types
//!
//! AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY MANUALLY
//! Source: schemas/*.schema.json
//! Generated by: pnpm run codegen

${modules.join('\n')}

// Re-export all types at the generated module level
pub use common_types::*;

${schemas.map(s => `pub use ${toSnakeCase(s.typeName)}::*;`).join('\n')}

/// Schema version constants
pub const SCHEMA_VERSIONS: &[(&str, u32)] = &[
${schemas.map(s => `    ("${s.typeName}", ${s.schemaVersion}),`).join('\n')}
];

/// Latest schema version
pub const LATEST_SCHEMA_VERSION: u32 = ${schemas[0]?.schemaVersion ?? 1};
`;

  writeFile(path.join(outputDir, 'mod.rs'), content);
}

/**
 * Generate individual Rust type file for a schema.
 */
function generateRustTypeFile(schema: LoadedSchema, outputDir: string): void {
  const typeName = schema.typeName;
  const moduleName = toSnakeCase(typeName);
  const content = generateRustStruct(typeName, schema);

  writeFile(path.join(outputDir, `${moduleName}.rs`), content);
}

/**
 * Generate Rust struct from JSON Schema properties.
 *
 * Strategy:
 * - Common ref enums (ManuscriptPhase, etc.) → import from common_types
 * - SourceAnchor ref → import from common_types
 * - Inline enums → use String (future: generate per-file enums)
 * - $-prefixed fields → #[serde(rename = "$xxx")] + pub dollar_xxx: ...
 */
function generateRustStruct(typeName: string, schema: LoadedSchema): string {
  const schemaContent = schema.schemaContent;
  const properties = (schemaContent.properties || {}) as Record<string, unknown>;
  const requiredFields = (schemaContent.required || []) as string[];

  const fields: string[] = [];
  const commonImports: Set<string> = new Set();

  for (const [propName, propDef] of Object.entries(properties)) {
    const def = propDef as Record<string, unknown>;
    const isRequired = requiredFields.includes(propName);
    const { rustType, commonImport } = resolveRustType(def, propName);

    if (commonImport) {
      commonImports.add(commonImport);
    }

    // Handle nullable types (type: ["string", "null"])
    const isNullable = Array.isArray(def.type) && def.type.includes('null');
    const finalType = isNullable ? stripOuterOption(rustType) : rustType;
    const optionalWrap = isRequired ? finalType : `Option<${finalType}>`;

    // serde attributes
    const serdeSkip = !isRequired ? '#[serde(skip_serializing_if = "Option::is_none")]' : '';

    const needsRename = propName.startsWith('$') || RUST_RESERVED_WORDS.has(propName);
    const rustFieldName = propName.startsWith('$')
      ? `dollar_${propName.slice(1)}`
      : RUST_RESERVED_WORDS.has(propName)
        ? `r#${propName}`
        : propName;

    if (needsRename) {
      fields.push(`    #[serde(rename = "${propName}")]`);
    }
    if (serdeSkip) {
      fields.push(`    ${serdeSkip}`);
    }
    fields.push(`    pub ${rustFieldName}: ${optionalWrap},`);
  }

  // Build use statements
  const importsArr = [...commonImports].sort();
  const useCommon = importsArr.length > 0
    ? `use crate::generated::common_types::{${importsArr.join(', ')}};`
    : '';

  return `//! ${schemaContent.title || typeName}
//!
//! ${schemaContent.description || 'Generated from JSON Schema'}
//!
//! @schema_version ${schema.schemaVersion}
//! @source ${schema.fileName}

use serde::{Deserialize, Serialize};

${useCommon}

/// ${schemaContent.title || typeName}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub struct ${typeName} {
${fields.join('\n')}
}
`;
}

/**
 * Resolve a property definition to a Rust type.
 * Returns { rustType, commonImport? } where commonImport is a common_types export name.
 */
function resolveRustType(
  propDef: Record<string, unknown>,
  propName: string,
): { rustType: string; commonImport?: string } {
  const ref = propDef.$ref as string | undefined;
  const type = propDef.type;

  // Handle $ref
  if (ref) {
    const defName = resolveRef(ref);
    if (defName === 'SourceAnchor') {
      return { rustType: 'SourceAnchor', commonImport: 'SourceAnchor' };
    }
    if (defName && isCommonEnum(defName)) {
      return { rustType: defName, commonImport: defName };
    }
    if (defName) {
      return { rustType: getCommonRustType(defName) };
    }
    return { rustType: 'serde_json::Value' };
  }

  // Handle type arrays (e.g., ["string", "null"])
  if (Array.isArray(type)) {
    const nonNullTypes = type.filter(t => t !== 'null');
    const hasNull = type.includes('null');
    if (nonNullTypes.length === 1) {
      const base = resolveSingleRustType(nonNullTypes[0], propDef, propName);
      // Caller handles Option wrapping; avoid double-wrap
      return { rustType: hasNull ? stripOuterOption(base) : base };
    }
    return { rustType: 'serde_json::Value' };
  }

  return { rustType: resolveSingleRustType(type as string, propDef, propName) };
}

/**
 * Strip outer Option<...> from a Rust type string.
 */
function stripOuterOption(rustType: string): string {
  if (rustType.startsWith('Option<') && rustType.endsWith('>')) {
    return rustType.slice(7, -1);
  }
  return rustType;
}

/**
 * Resolve a single JSON Schema type to Rust.
 */
function resolveSingleRustType(
  type: string,
  propDef: Record<string, unknown>,
  propName: string,
): string {
  switch (type) {
    case 'string':
      // Inline enum — use String for now (future: generate per-file enums)
      if (propDef.enum) {
        return 'String';
      }
      return 'String';
    case 'number':
      return 'f64';
    case 'integer':
      if (propName === 'schema_version') return 'u32';
      if (propDef.minimum === 0) return 'u64';
      return 'i64';
    case 'boolean':
      return 'bool';
    case 'array': {
      if (propDef.items) {
        const items = propDef.items as Record<string, unknown>;
        if (items.type === 'object' && items.properties) {
          // Complex inline object in array → use serde_json::Value
          return "Vec<serde_json::Value>";
        }
        const { rustType } = resolveRustType(items, propName);
        return `Vec<${rustType}>`;
      }
      return 'Vec<serde_json::Value>';
    }
    case 'object': {
      if (propDef.properties) {
        // Inline object → serde_json::Value (future: generate inline struct)
        return 'serde_json::Value';
      }
      return 'serde_json::Value';
    }
    default:
      return 'serde_json::Value';
  }
}

/**
 * Get Rust type for a common definition name.
 */
function getCommonRustType(defName: string): string {
  switch (defName) {
    case 'SchemaVersion':
      return 'u32';
    case 'DeltaSequence':
      return 'u64';
    case 'Timestamp':
    case 'WorldId':
    case 'CreatorId':
    case 'UserId':
    case 'KeyBlockId':
    case 'TimelineEventId':
    case 'BundleId':
    case 'CommandId':
    case 'WorkspaceId':
      return 'String';
    default:
      return 'serde_json::Value';
  }
}

/**
 * Generate common_types.rs with shared Rust types and enums.
 */
function generateRustCommonTypes(outputDir: string): void {
  const content = `//! Nexus Common Types
//!
//! Shared type definitions extracted from schemas/common/common.schema.json
//!
//! AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY MANUALLY
//! Generated by: pnpm run codegen

use serde::{Deserialize, Serialize};

// ── Type aliases ──────────────────────────────────────────────────────

/// Schema version as integer (e.g., 1)
pub type SchemaVersion = u32;

/// ISO 8601 / RFC 3339 UTC datetime string
pub type Timestamp = String;

/// World ID (prefix: 'wld_')
pub type WorldId = String;

/// Creator ID (prefix: 'ctr_')
pub type CreatorId = String;

/// User ID (prefix: 'usr_')
pub type UserId = String;

/// KeyBlock ID (prefix: 'kb_')
pub type KeyBlockId = String;

/// TimelineEvent ID (prefix: 'evt_')
pub type TimelineEventId = String;

/// DeltaBundle ID (prefix: 'bdl_')
pub type BundleId = String;

/// SyncCommand ID (prefix: 'cmd_')
pub type CommandId = String;

/// Workspace ID (prefix: 'wrk_')
pub type WorkspaceId = String;

/// Monotonically increasing sequence number for deltas
pub type DeltaSequence = u64;

// ── Enums ─────────────────────────────────────────────────────────────

/// Manuscript lifecycle phase (data-model-v1.md §7, §5.9B)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ManuscriptPhase {
    Brainstorm,
    Draft,
    Review,
    Finalize,
    Published,
}

/// World timeline evolution policy (data-model-v1.md §5.3)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TimePolicy {
    Manual,
    OwnerDriven,
    EventDriven,
}

/// Visibility/access level (data-model-v1.md §5.3)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Visibility {
    Private,
    Unlisted,
    Public,
}

/// KeyBlock content type (data-model-v1.md §5.5)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum BlockType {
    Character,
    Ability,
    Scene,
    Organization,
    Item,
    Conflict,
    InfoPoint,
    Event,
}

/// MemoryItem type (data-model-v1.md §5.8)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MemoryType {
    Canon,
    Working,
    Experience,
}

/// DeltaBundle type (data-model-v1.md §5.11)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum BundleType {
    WorldSync,
    MemorySync,
    PublishMetadata,
}

// ── SourceAnchor (from source-anchor.schema.json) ─────────────────────

/// Source anchor for provenance — references platform Story summary entities.
/// Source: schemas/common/source-anchor.schema.json
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub struct SourceAnchor {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub story_summary_refs: Option<Vec<SourceSummaryRef>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub excerpt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
}

/// Reference to a platform Story summary entity.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub struct SourceSummaryRef {
    pub story_manifest_id: String,
    pub summary_unit_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_kind: Option<String>,
}
`;

  writeFile(path.join(outputDir, 'common_types.rs'), content);
}
