import { LoadedSchema } from './schema-loader';
import { resolveRef, isCommonEnum, getCommonBaseType } from './schema-loader';
import { resolveFromRoot, writeFile, logger } from './utils';
import path from 'path';

/**
 * Generate TypeScript types from schemas.
 */
export function generateTSTypes(schemas: LoadedSchema[]): void {
  const outputDir = resolveFromRoot('packages', 'nexus-contracts', 'src', 'generated');
  logger.info(`Generating TypeScript types to: ${outputDir}`);

  // Filter schemas that need struct generation (have properties)
  const structSchemas = schemas.filter(s => !s.isDefinitionsOnly);

  // Generate common types file first
  generateCommonTypesFile(outputDir);

  // Generate individual type files
  for (const schema of structSchemas) {
    generateTSTypeFile(schema, outputDir);
  }

  // Generate index.ts with re-exports
  generateTSIndex(structSchemas, outputDir);

  logger.success(`Generated TypeScript types for ${structSchemas.length} schema(s) (+ common types)`);
}

/**
 * Generate index.ts with re-exports
 */
function generateTSIndex(schemas: LoadedSchema[], outputDir: string): void {
  const exports: string[] = [];

  for (const schema of schemas) {
    exports.push(schema.typeName);
  }

  const content = `/**
 * Nexus Wire Contracts - Generated TypeScript Types
 *
 * AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY MANUALLY
 * Source: schemas/*.schema.json
 * Generated by: pnpm run codegen
 */

// Common types (type aliases, enums, SourceAnchor)
export * from './CommonTypes';

// Schema version constants
export const SCHEMA_VERSIONS: Record<string, number> = {
${schemas.map(s => `  ${s.typeName}: ${s.schemaVersion},`).join('\n')}
};

// Latest schema version
export const LATEST_SCHEMA_VERSION = ${schemas[0]?.schemaVersion ?? 1};
`;

  writeFile(path.join(outputDir, 'index.ts'), content);
}

/**
 * Generate individual TypeScript type file for a schema.
 *
 * Strategy:
 * - Common ref types (from $ref to common.schema.json#/definitions/*) → import from CommonTypes
 * - SourceAnchor ref → import from CommonTypes
 * - Inline enums (enum values on non-$ref properties) → define as type alias in this file
 * - All other types → resolve inline
 */
function generateTSTypeFile(schema: LoadedSchema, outputDir: string): void {
  const typeName = schema.typeName;
  const schemaContent = schema.schemaContent;
  const properties = (schemaContent.properties || {}) as Record<string, unknown>;
  const requiredFields = (schemaContent.required || []) as string[];

  // Collect information during property traversal
  const commonTypeImports: Set<string> = new Set(['SchemaVersion']);
  const inlineEnums: Map<string, string[]> = new Map(); // name → values
  const fields: string[] = [];

  // Check if SourceAnchor is referenced anywhere in this schema
  const schemaJSON = JSON.stringify(schemaContent);
  if (schemaJSON.includes('source-anchor.schema.json')) {
    commonTypeImports.add('SourceAnchor');
  }

  for (const [propName, propDef] of Object.entries(properties)) {
    const def = propDef as Record<string, unknown>;
    const isRequired = requiredFields.includes(propName);
    const { tsType, commonRef } = resolveTSType(def, propName, inlineEnums);
    if (commonRef) {
      commonTypeImports.add(commonRef);
    }
    const optionalMark = isRequired ? '' : '?';
    fields.push(`  ${propName}${optionalMark}: ${tsType};`);
  }

  // Build file content
  let content = `/**
 * ${schemaContent.title || typeName}
 *
 * ${schemaContent.description || 'Generated from JSON Schema'}
 *
 * @schema_version ${schema.schemaVersion}
 * @source ${schema.fileName}
 */
`;

  // Import from CommonTypes
  const imports = [...commonTypeImports].sort();
  if (imports.length > 0) {
    content += `import type { ${imports.join(', ')} } from './CommonTypes';\n`;
  }

  // Define inline enums as type aliases
  for (const [enumName, values] of inlineEnums) {
    content += `\n/** Inline enum type */\nexport type ${enumName} = ${values.map(v => `'${v}'`).join(' | ')};\n`;
  }

  // Main interface
  content += `\nexport interface ${typeName} {\n${fields.join('\n')}\n}\n`;

  writeFile(path.join(outputDir, `${typeName}.ts`), content);
}

/**
 * Resolve a property definition to a TypeScript type string.
 * Returns { tsType, commonRef? } where commonRef is set if this maps to a CommonTypes export.
 */
function resolveTSType(
  propDef: Record<string, unknown>,
  propName: string,
  inlineEnums: Map<string, string[]>,
): { tsType: string; commonRef?: string } {
  const ref = propDef.$ref as string | undefined;
  const type = propDef.type;

  // Handle $ref
  if (ref) {
    const defName = resolveRef(ref);
    if (defName === 'SourceAnchor') {
      return { tsType: 'SourceAnchor', commonRef: 'SourceAnchor' };
    }
    if (defName && isCommonEnum(defName)) {
      return { tsType: defName, commonRef: defName };
    }
    if (defName) {
      return { tsType: getCommonBaseType(defName), commonRef: undefined };
    }
    return { tsType: 'unknown' };
  }

  // Handle type arrays (e.g., ["string", "null"])
  if (Array.isArray(type)) {
    const nonNullTypes = type.filter(t => t !== 'null');
    const hasNull = type.includes('null');
    if (nonNullTypes.length === 1) {
      const base = resolveSingleTSType(nonNullTypes[0], propDef, propName, inlineEnums);
      return { tsType: hasNull ? `${base} | null` : base };
    }
    return { tsType: 'unknown' };
  }

  return { tsType: resolveSingleTSType(type as string, propDef, propName, inlineEnums) };
}

/**
 * Resolve a single JSON Schema type to TypeScript.
 */
function resolveSingleTSType(
  type: string,
  propDef: Record<string, unknown>,
  propName: string,
  inlineEnums: Map<string, string[]>,
): string {
  switch (type) {
    case 'string':
      if (propDef.enum) {
        const values = propDef.enum as string[];
        const enumName = toPascalCase(propName);
        inlineEnums.set(enumName, values);
        return enumName;
      }
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array': {
      if (propDef.items) {
        const items = propDef.items as Record<string, unknown>;
        // Check if items is an object with its own properties
        if (items.type === 'object' && items.properties) {
          // Inline object inside array — build an inline type
          return buildInlineObjectType(items, inlineEnums) + '[]';
        }
        const { tsType } = resolveTSType(items, propName, inlineEnums);
        return `${tsType}[]`;
      }
      return 'unknown[]';
    }
    case 'object': {
      if (propDef.properties) {
        return buildInlineObjectType(propDef, inlineEnums);
      }
      return 'Record<string, unknown>';
    }
    default:
      return 'unknown';
  }
}

/**
 * Build an inline object type from a property definition with properties.
 */
function buildInlineObjectType(
  objDef: Record<string, unknown>,
  inlineEnums: Map<string, string[]>,
): string {
  const props = (objDef.properties || {}) as Record<string, unknown>;
  const required = (objDef.required || []) as string[];
  const parts: string[] = [];

  for (const [k, v] of Object.entries(props)) {
    const isReq = required.includes(k);
    const { tsType } = resolveTSType(v as Record<string, unknown>, k, inlineEnums);
    parts.push(`${k}${isReq ? '' : '?'}: ${tsType}`);
  }

  return `{ ${parts.join('; ')} }`;
}

/**
 * Convert a snake_case property name to PascalCase.
 * e.g., "bundle_type" -> "BundleType", "delta_type" -> "DeltaType"
 */
function toPascalCase(snakeStr: string): string {
  return snakeStr
    .split('_')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

/**
 * Generate CommonTypes.ts with shared type definitions.
 * Contains: type aliases, common enums, and SourceAnchor interface.
 */
function generateCommonTypesFile(outputDir: string): void {
  const aliases = [
    { name: 'SchemaVersion', type: 'number', desc: 'Schema version as integer (e.g., 1)' },
    { name: 'Timestamp', type: 'string', desc: 'ISO 8601 / RFC 3339 UTC datetime string' },
    { name: 'WorldId', type: 'string', desc: "World ID (prefix: 'wld_')" },
    { name: 'CreatorId', type: 'string', desc: "Creator ID (prefix: 'ctr_')" },
    { name: 'UserId', type: 'string', desc: "User ID (prefix: 'usr_')" },
    { name: 'KeyBlockId', type: 'string', desc: "KeyBlock ID (prefix: 'kb_')" },
    { name: 'TimelineEventId', type: 'string', desc: "TimelineEvent ID (prefix: 'evt_')" },
    { name: 'BundleId', type: 'string', desc: "DeltaBundle ID (prefix: 'bdl_')" },
    { name: 'CommandId', type: 'string', desc: "SyncCommand ID (prefix: 'cmd_')" },
    { name: 'WorkspaceId', type: 'string', desc: "Workspace ID (prefix: 'wrk_')" },
    { name: 'DeltaSequence', type: 'number', desc: 'Monotonically increasing sequence number for deltas' },
  ];

  const enums = [
    {
      name: 'ManuscriptPhase',
      values: ['brainstorm', 'draft', 'review', 'finalize', 'published'],
      desc: 'Manuscript lifecycle phase (data-model-v1.md §7, §5.9B)',
    },
    {
      name: 'TimePolicy',
      values: ['manual', 'owner_driven', 'event_driven'],
      desc: 'World timeline evolution policy (data-model-v1.md §5.3)',
    },
    {
      name: 'Visibility',
      values: ['private', 'unlisted', 'public'],
      desc: 'Visibility/access level (data-model-v1.md §5.3)',
    },
    {
      name: 'BlockType',
      values: ['character', 'ability', 'scene', 'organization', 'item', 'conflict', 'info_point', 'event'],
      desc: 'KeyBlock content type (data-model-v1.md §5.5)',
    },
    {
      name: 'MemoryType',
      values: ['canon', 'working', 'experience'],
      desc: 'MemoryItem type (data-model-v1.md §5.8)',
    },
    {
      name: 'BundleType',
      values: ['world_sync', 'memory_sync', 'publish_metadata'],
      desc: 'DeltaBundle type (data-model-v1.md §5.11)',
    },
  ];

  let content = `/**
 * Nexus Common Types
 *
 * Shared type definitions extracted from schemas/common/common.schema.json
 *
 * AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY MANUALLY
 * Generated by: pnpm run codegen
 */

`;

  for (const alias of aliases) {
    content += `/** ${alias.desc} */\nexport type ${alias.name} = ${alias.type};\n\n`;
  }

  for (const en of enums) {
    content += `/** ${en.desc} */\nexport type ${en.name} = ${en.values.map(v => `'${v}'`).join(' | ')};\n\n`;
  }

  content += `/**
 * SourceAnchor - Value object for referencing platform Story summary entities.
 * Source: schemas/common/source-anchor.schema.json
 */
export interface SourceAnchor {
  story_summary_refs?: SourceSummaryRef[];
  excerpt?: string;
  summary?: string;
}

export interface SourceSummaryRef {
  story_manifest_id: string;
  summary_unit_id: string;
  unit_kind?: string;
}
`;

  writeFile(path.join(outputDir, 'CommonTypes.ts'), content);
}
