import { LoadedSchema, COMMON_DEFINITIONS } from './schema-loader';
import { resolveRef, isCommonEnum, getCommonBaseType } from './schema-loader';
import { resolveFromRoot, writeFile, logger, removeStaleGeneratedFiles, maxSchemaVersion } from './utils';
import path from 'path';

/**
 * Check if a schema has object definitions with properties.
 */
function schemaHasObjectDefinitions(schema: LoadedSchema): boolean {
  const definitions = getDefinitions(schema);
  if (!definitions) return false;
  return Object.values(definitions).some(
    (def: any) => def.type === 'object' && def.properties && Object.keys(def.properties).length > 0,
  );
}

/**
 * Get definitions from a schema (supports both `definitions` and `$defs`).
 */
function getDefinitions(schema: LoadedSchema): Record<string, Record<string, unknown>> | undefined {
  const d = schema.schemaContent.definitions || schema.schemaContent.$defs;
  return d as Record<string, Record<string, unknown>> | undefined;
}

/**
 * Generate TypeScript types from schemas.
 */
export function generateTSTypes(schemas: LoadedSchema[]): void {
  const outputDir = resolveFromRoot('packages', 'nexus-contracts', 'src', 'generated');
  logger.info(`Generating TypeScript types to: ${outputDir}`);

  // Generate common types file first
  generateCommonTypesFile(outputDir);

  // Collect schemas that produce type files
  const schemasWithTypes: LoadedSchema[] = [];

  for (const schema of schemas) {
    if (schema.isExplicitlySkipped) continue;

    const hasTopLevel = !schema.isDefinitionsOnly;
    const hasDefs = schemaHasObjectDefinitions(schema);

    if (!hasTopLevel && !hasDefs) continue;

    schemasWithTypes.push(schema);

    // Generate individual type files
    generateTSTypeFile(schema, outputDir, hasTopLevel, hasDefs);
  }

  // Generate index.ts with re-exports
  generateTSIndex(schemasWithTypes, outputDir);

  const keepTs = new Set(['index.ts', 'CommonTypes.ts']);
  for (const s of schemasWithTypes) {
    keepTs.add(`${s.typeName}.ts`);
  }
  removeStaleGeneratedFiles(outputDir, keepTs, '.ts');

  logger.success(`Generated TypeScript types for ${schemasWithTypes.length} schema(s) (+ common types)`);
}

/**
 * Generate index.ts with re-exports
 */
function generateTSIndex(schemas: LoadedSchema[], outputDir: string): void {
  const perSchemaExports = schemas.map(s => `export * from './${s.typeName}';`).join('\n');
  const latest = maxSchemaVersion(schemas.map(s => s.schemaVersion));

  const content = `/**
 * Nexus Wire Contracts - Generated TypeScript Types
 *
 * AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY MANUALLY
 * Source: schemas/*.schema.json
 * Generated by: pnpm run codegen
 */

// Common types (type aliases, enums, SourceAnchor)
export * from './CommonTypes';

// Per-schema modules (stable order: sorted schema paths at load time)
${perSchemaExports}

// Schema version constants
export const SCHEMA_VERSIONS: Record<string, number> = {
${schemas.map(s => `  ${s.typeName}: ${s.schemaVersion},`).join('\n')}
};

// Highest schema_version among emitted contract schemas
export const LATEST_SCHEMA_VERSION = ${latest};
`;

  writeFile(path.join(outputDir, 'index.ts'), content);
}

/**
 * Generate TypeScript type file(s) for a schema.
 *
 * Handles three cases:
 * 1. Top-level properties only → single interface
 * 2. Definitions only → one interface per definition
 * 3. Both → main interface + definition interfaces (all in same file)
 */
function generateTSTypeFile(
  schema: LoadedSchema,
  outputDir: string,
  hasTopLevel: boolean,
  hasDefs: boolean,
): void {
  let content = `/**
 * ${schema.schemaContent.title || schema.typeName}
 *
 * ${schema.schemaContent.description || 'Generated from JSON Schema'}
 *
 * @schema_version ${schema.schemaVersion}
 * @source ${schema.fileName}
 */
`;

  const localDefinitions = hasDefs ? getDefinitions(schema) : undefined;
  const commonTypeImports: Set<string> = new Set(['SchemaVersion']);
  const allInlineEnums: Map<string, string[]> = new Map();
  const definitionNames: string[] = [];

  // Check if SourceAnchor is referenced anywhere in this schema
  const schemaJSON = JSON.stringify(schema.schemaContent);
  if (schemaJSON.includes('source-anchor.schema.json')) {
    commonTypeImports.add('SourceAnchor');
  }

  // Generate main interface from top-level properties
  if (hasTopLevel) {
    const { fieldsText, imports } = generateTSTypeFields(
      schema.schemaContent,
      schema.typeName,
      commonTypeImports,
      allInlineEnums,
      localDefinitions,
    );
    for (const imp of imports) commonTypeImports.add(imp);
    content += fieldsText + '\n';
  }

  // Generate interfaces from definitions
  if (hasDefs && localDefinitions) {
    for (const [defName, defContent] of Object.entries(localDefinitions)) {
      const def = defContent as Record<string, unknown>;
      if (def.type !== 'object' || !def.properties) continue;

      definitionNames.push(defName);
      const { fieldsText, imports } = generateTSTypeFields(
        def,
        defName,
        commonTypeImports,
        allInlineEnums,
        localDefinitions,
      );
      for (const imp of imports) commonTypeImports.add(imp);
      content += fieldsText + '\n';
    }
  }

  // Build imports
  const imports = [...commonTypeImports].sort();
  if (imports.length > 0) {
    content = `import type { ${imports.join(', ')} } from './CommonTypes';\n\n` + content;
  }

  // Define inline enums as type aliases
  let enumBlock = '';
  for (const [enumName, values] of allInlineEnums) {
    enumBlock += `\n/** Inline enum type */\nexport type ${enumName} = ${values.map(v => `'${v}'`).join(' | ')};\n`;
  }

  // Insert enum block after imports
  if (enumBlock) {
    const importEnd = content.indexOf('*/', content.indexOf('import type'));
    if (importEnd !== -1) {
      const afterImport = content.indexOf('\n', importEnd) + 1;
      content = content.slice(0, afterImport) + enumBlock + '\n' + content.slice(afterImport);
    }
  }

  writeFile(path.join(outputDir, `${schema.typeName}.ts`), content);
}

/**
 * Generate TypeScript interface fields from a schema or definition object.
 * Returns the interface text and any common type imports needed.
 */
function generateTSTypeFields(
  schemaContent: Record<string, unknown>,
  typeName: string,
  existingImports: Set<string>,
  inlineEnums: Map<string, string[]>,
  localDefinitions?: Record<string, Record<string, unknown>>,
): { fieldsText: string; imports: Set<string> } {
  const properties = (schemaContent.properties || {}) as Record<string, unknown>;
  const requiredFields = (schemaContent.required || []) as string[];
  const newImports: Set<string> = new Set();
  const fields: string[] = [];

  for (const [propName, propDef] of Object.entries(properties)) {
    const def = propDef as Record<string, unknown>;
    const isRequired = requiredFields.includes(propName);
    const { tsType, commonRef } = resolveTSType(def, propName, inlineEnums, localDefinitions, typeName);
    if (commonRef) {
      newImports.add(commonRef);
    }
    const optionalMark = isRequired ? '' : '?';
    // Quote property names that contain hyphens (invalid in unquoted TS identifiers)
    const tsPropName = /-/.test(propName) ? `'${propName}'` : propName;
    fields.push(`  ${tsPropName}${optionalMark}: ${tsType};`);
  }

  const desc = (schemaContent.description || typeName) as string;
  const fieldsText = `/** ${desc} */\nexport interface ${typeName} {\n${fields.join('\n')}\n}`;
  return { fieldsText, imports: newImports };
}

/**
 * Resolve a property definition to a TypeScript type string.
 * Returns { tsType, commonRef? } where commonRef is set if this maps to a CommonTypes export.
 *
 * @param inlineEnumPathPrefix PascalCase path prefix for inline string enums (e.g. Creator, CreatorMetadata)
 *        so barrel `export *` does not collide on names like `Status` across modules.
 */
function resolveTSType(
  propDef: Record<string, unknown>,
  propName: string,
  inlineEnums: Map<string, string[]>,
  localDefinitions: Record<string, Record<string, unknown>> | undefined,
  inlineEnumPathPrefix: string,
): { tsType: string; commonRef?: string } {
  const ref = propDef.$ref as string | undefined;
  const type = propDef.type;

  // Handle $ref
  if (ref) {
    const defName = resolveRef(ref);
    if (defName === 'SourceAnchor') {
      return { tsType: 'SourceAnchor', commonRef: 'SourceAnchor' };
    }
    if (defName && isCommonEnum(defName)) {
      return { tsType: defName, commonRef: defName };
    }
    // Check local definitions (e.g., #/definitions/AgentEntry within same schema)
    if (defName && localDefinitions && defName in localDefinitions) {
      return { tsType: defName };
    }
    if (defName) {
      return { tsType: getCommonBaseType(defName), commonRef: undefined };
    }
    return { tsType: 'unknown' };
  }

  // Handle type arrays (e.g., ["string", "null"])
  if (Array.isArray(type)) {
    const nonNullTypes = type.filter(t => t !== 'null');
    const hasNull = type.includes('null');
    if (nonNullTypes.length === 1) {
      const base = resolveSingleTSType(
        nonNullTypes[0],
        propDef,
        propName,
        inlineEnums,
        localDefinitions,
        inlineEnumPathPrefix,
      );
      return { tsType: hasNull ? `${base} | null` : base };
    }
    return { tsType: 'unknown' };
  }

  return {
    tsType: resolveSingleTSType(
      type as string,
      propDef,
      propName,
      inlineEnums,
      localDefinitions,
      inlineEnumPathPrefix,
    ),
  };
}

/**
 * Resolve a single JSON Schema type to TypeScript.
 */
function resolveSingleTSType(
  type: string,
  propDef: Record<string, unknown>,
  propName: string,
  inlineEnums: Map<string, string[]>,
  localDefinitions: Record<string, Record<string, unknown>> | undefined,
  inlineEnumPathPrefix: string,
): string {
  switch (type) {
    case 'string':
      if (propDef.enum) {
        const values = propDef.enum as string[];
        // Empty propName: caller already folded the segment (e.g. array item type for `memory_kinds`).
        const enumName =
          propName === '' ? inlineEnumPathPrefix : `${inlineEnumPathPrefix}${toPascalCase(propName)}`;
        inlineEnums.set(enumName, values);
        return enumName;
      }
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array': {
      if (propDef.items) {
        const items = propDef.items as Record<string, unknown>;
        // Check if items is an object with its own properties
        if (items.type === 'object' && items.properties) {
          const path = `${inlineEnumPathPrefix}${toPascalCase(propName)}`;
          return buildInlineObjectType(items, inlineEnums, localDefinitions, path) + '[]';
        }
        const { tsType } = resolveTSType(
          items,
          '',
          inlineEnums,
          localDefinitions,
          `${inlineEnumPathPrefix}${toPascalCase(propName)}`,
        );
        return `${tsType}[]`;
      }
      return 'unknown[]';
    }
    case 'object': {
      if (propDef.properties) {
        const path = `${inlineEnumPathPrefix}${toPascalCase(propName)}`;
        return buildInlineObjectType(propDef, inlineEnums, localDefinitions, path);
      }
      return 'Record<string, unknown>';
    }
    default:
      return 'unknown';
  }
}

/**
 * Build an inline object type from a property definition with properties.
 */
function buildInlineObjectType(
  objDef: Record<string, unknown>,
  inlineEnums: Map<string, string[]>,
  localDefinitions: Record<string, Record<string, unknown>> | undefined,
  /** PascalCase path to this anonymous object (parent prefix + property segment). */
  objectPathPrefix: string,
): string {
  const props = (objDef.properties || {}) as Record<string, unknown>;
  const required = (objDef.required || []) as string[];
  const parts: string[] = [];

  for (const [k, v] of Object.entries(props)) {
    const isReq = required.includes(k);
    const { tsType } = resolveTSType(v as Record<string, unknown>, k, inlineEnums, localDefinitions, objectPathPrefix);
    parts.push(`${k}${isReq ? '' : '?'}: ${tsType}`);
  }

  return `{ ${parts.join('; ')} }`;
}

/**
 * Convert a snake_case property name to PascalCase.
 * e.g., "bundle_type" -> "BundleType", "delta_type" -> "DeltaType"
 */
function toPascalCase(snakeStr: string): string {
  return snakeStr
    .split('_')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

/**
 * Generate CommonTypes.ts with shared type definitions.
 * Driven from COMMON_DEFINITIONS map (populated from common.schema.json).
 */
function generateCommonTypesFile(outputDir: string): void {
  const typeAliases: Array<{ name: string; type: string; desc: string }> = [];
  const enums: Array<{ name: string; values: string[]; desc: string }> = [];

  for (const [name, def] of COMMON_DEFINITIONS.entries()) {
    if (def.enum) {
      enums.push({
        name,
        values: def.enum,
        desc: def.description || `Enum type ${name}`,
      });
    } else {
      const tsType = def.type === 'integer' ? 'number' : 'string';
      typeAliases.push({
        name,
        type: tsType,
        desc: def.description || `Type alias ${name}`,
      });
    }
  }

  let content = `/**
 * Nexus Common Types
 *
 * Shared type definitions extracted from schemas/common/common.schema.json
 *
 * AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY MANUALLY
 * Generated by: pnpm run codegen
 */

`;

  for (const alias of typeAliases) {
    content += `/** ${alias.desc} */\nexport type ${alias.name} = ${alias.type};\n\n`;
  }

  for (const en of enums) {
    content += `/** ${en.desc} */\nexport type ${en.name} = ${en.values.map(v => `'${v}'`).join(' | ')};\n\n`;
  }

  content += `/**
 * SourceAnchor - Value object for referencing platform Story summary entities.
 * Source: schemas/common/source-anchor.schema.json
 */
export interface SourceAnchor {
  story_summary_refs?: SourceSummaryRef[];
  excerpt?: string;
  summary?: string;
}

export interface SourceSummaryRef {
  story_manifest_id: string;
  summary_unit_id: string;
  unit_kind?: string;
}
`;

  writeFile(path.join(outputDir, 'CommonTypes.ts'), content);
}
