//! Enum conversion utilities for generated contract types.
//!
//! Provides `as_str()` inherent methods for enum types generated from JSON Schema,
//! plus `Display` / `FromStr` for `RuntimeMode` (a local-only type NOT generated by
//! typify). Schema string enums get `Display` + `FromStr` from typify directly
//! (plan v1.138 T5); this file adds only the `as_str()` convenience that typify
//! does not emit.
//!
//! This is the project's hand-maintained extension surface for generated enums.
//! When a JSON Schema adds or renames enum values, update the `as_str()` match
//! arms in this file in the same commit and verify with `cargo test -p
//! nexus-contracts`. See `crates/nexus-contracts/AGENTS.md` for the full rule.

use crate::common_types::{
    AccountStatus, AgentProfileStatus, BindingStatus, BlockType, CommandOrigin, CommandStatus,
    CommandType, CreatorStatus, DeliveryState, DeltaOperation, DeltaType, ForkBranchStatus,
    KeyBlockStatus, ManifestType, ManuscriptStorage, MembershipRole, MembershipStatus, MemoryKind,
    MemoryStatus, PairingSource, PairingStatus, ProfileKind, PublishStoryOutcome,
    ReferenceSourceType, RegistrationSource, ScanStatus, SelectionMode, StoryManifestStatus,
    SubscriptionTier, TimelineEventStatus, TimelineEventType, VerificationStatus, WorldStatus,
};
use crate::generated::daemon_api::canvas::world_kb::world_kb_relationship_kind::WorldKbRelationshipKind;
use crate::generated::daemon_api::works::chapters::chapter_status::ChapterStatus;
// Generated enums that consumers call `.as_str()` on at conversion boundaries
// (plan v1.138 P1). typify emits `Display`+`FromStr` for these but not the
// `as_str()` inherent method the boundary code relies on. The three whose
// names collide with `common_types` imports (`KeyBlockStatus`, `PairingStatus`,
// `CreatorStatus`) are implemented via fully-qualified paths below to avoid
// ambiguous imports; only the mangled-name enums are imported here.
use crate::generated::domain::creator::CreatorRegistrationSource;
use crate::generated::domain::pairing::PairingPairingSource;
use crate::generated::domain::user::UserAccountStatus;
use crate::generated::domain::user::UserSubscriptionTier;
use crate::local::domain::runtime_mode::RuntimeMode;
use std::fmt;
use std::str::FromStr;

// ── Display implementations for tracing/logging ──────────────────────────
// Note: typify generates `Display` + `FromStr` for all schema string enums
// (plan v1.138 T5). Only `RuntimeMode` (a local-only type, NOT typify-generated)
// retains a hand-written `Display` + `FromStr` here. Schema enums keep their
// hand-written `as_str()` inherent methods below — typify does not emit those.

impl fmt::Display for RuntimeMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// ── as_str() implementations ─────────────────────────────────────────────

impl AccountStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Suspended => "suspended",
            Self::Deleted => "deleted",
        }
    }
}

impl SubscriptionTier {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Free => "free",
            Self::Pro => "pro",
            Self::Studio => "studio",
            Self::Enterprise => "enterprise",
        }
    }
}

// V1.54 P1: BlockType as_str — supports novel, game-bible, script (V1.55 P3),
// and era (V1.123 P1) variants.
impl BlockType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Character => "character",
            Self::Ability => "ability",
            Self::Scene => "scene",
            Self::Organization => "organization",
            Self::Item => "item",
            Self::Conflict => "conflict",
            Self::InfoPoint => "info_point",
            Self::Event => "event",
            Self::Species => "species",
            Self::Faction => "faction",
            Self::MagicSystem => "magic_system",
            Self::Technology => "technology",
            Self::Deity => "deity",
            Self::Level => "level",
            Self::EconomyTier => "economy_tier",
            // V1.55 P3: script taxonomy
            Self::Dialogue => "dialogue",
            Self::Beat => "beat",
            Self::Act => "act",
            // V1.123 P1: Brief-era cross-profile world-shape marker
            Self::Era => "era",
        }
    }
}

// V1.74: WorldKbRelationshipKind as_str for daemon validation.
impl WorldKbRelationshipKind {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AlliedWith => "allied_with",
            Self::Opposes => "opposes",
            Self::ParentOf => "parent_of",
            Self::ChildOf => "child_of",
            Self::MemberOf => "member_of",
            Self::LocatedIn => "located_in",
            Self::RulesOver => "rules_over",
            Self::References => "references",
            Self::Serves => "serves",
            Self::RivalOf => "rival_of",
            Self::MentorOf => "mentor_of",
            Self::Custom => "custom",
        }
    }
}

impl CreatorStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Archived => "archived",
            Self::Locked => "locked",
        }
    }
}

impl RegistrationSource {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Cli => "cli",
            Self::WebAgent => "web_agent",
            Self::Platform => "platform",
        }
    }
}

impl WorldStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Paused => "paused",
            Self::Archived => "archived",
        }
    }
}

impl MembershipStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Invited => "invited",
            Self::Suspended => "suspended",
            Self::Removed => "removed",
        }
    }
}

impl MembershipRole {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Owner => "owner",
            Self::Maintainer => "maintainer",
            Self::Collaborator => "collaborator",
            Self::OfficialCreator => "official_creator",
        }
    }
}

impl PairingSource {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AutoCli => "auto_cli",
            Self::ManualWeb => "manual_web",
            Self::PlatformAuto => "platform_auto",
        }
    }
}

impl PairingStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Revoked => "revoked",
        }
    }
}

impl KeyBlockStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Provisional => "provisional",
            Self::Confirmed => "confirmed",
            Self::Deprecated => "deprecated",
            Self::Merged => "merged",
            Self::Deleted => "deleted",
        }
    }
}

impl TimelineEventType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::StoryAdvance => "story_advance",
            Self::StateUpdate => "state_update",
            Self::ForkMarker => "fork_marker",
            Self::OfficialProgression => "official_progression",
            Self::PublishMarker => "publish_marker",
        }
    }
}

impl TimelineEventStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Canon => "canon",
            Self::Provisional => "provisional",
            Self::Rejected => "rejected",
        }
    }
}

impl ForkBranchStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Archived => "archived",
        }
    }
}

impl VerificationStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Unverified => "unverified",
            Self::Requested => "requested",
            Self::Verified => "verified",
            Self::Rejected => "rejected",
        }
    }
}

impl MemoryKind {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::StorySummary => "story_summary",
            Self::ResearchMaterial => "research_material",
            Self::ReviewNote => "review_note",
            Self::CharacterNote => "character_note",
            Self::WorldBuilding => "world_building",
            Self::PlotOutline => "plot_outline",
            Self::ThemeAnalysis => "theme_analysis",
            Self::PersonalityCore => "personality_core",
            Self::Custom => "custom",
        }
    }
}

impl MemoryStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Superseded => "superseded",
            Self::Archived => "archived",
        }
    }
}

impl ManifestType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Chapter => "chapter",
            Self::Arc => "arc",
            Self::Story => "story",
            Self::Excerpt => "excerpt",
        }
    }
}

impl StoryManifestStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::SummaryReady => "summary_ready",
            Self::StagedForPublish => "staged_for_publish",
            Self::Published => "published",
            Self::Archived => "archived",
        }
    }
}

impl PublishStoryOutcome {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Submitted => "submitted",
            Self::Published => "published",
            Self::Rejected => "rejected",
            Self::InvalidState => "invalid_state",
        }
    }
}

impl ManuscriptStorage {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::LocalWorkspace => "local_workspace",
            Self::PlatformSandbox => "platform_sandbox",
        }
    }
}

impl ReferenceSourceType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::File => "file",
            Self::Pdf => "pdf",
            Self::Url => "url",
            Self::Note => "note",
        }
    }
}

impl ScanStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Scanned => "scanned",
            Self::Failed => "failed",
            Self::Ignored => "ignored",
        }
    }
}

impl CommandType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AdvanceWorld => "advance_world",
            Self::InjectFutureEvent => "inject_future_event",
            Self::ExtractKb => "extract_kb",
            Self::SyncPush => "sync_push",
            Self::SyncPull => "sync_pull",
            Self::ForkWorld => "fork_world",
            Self::PublishStory => "publish_story",
        }
    }
}

impl CommandOrigin {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::LocalUser => "local_user",
            Self::LocalAgent => "local_agent",
            Self::OfficialCreator => "official_creator",
            Self::System => "system",
        }
    }
}

impl CommandStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Running => "running",
            Self::Completed => "completed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        }
    }
}

impl DeltaType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::World => "world",
            Self::KeyBlock => "key_block",
            Self::TimelineEvent => "timeline_event",
            Self::ForkBranch => "fork_branch",
            Self::MemoryItem => "memory_item",
            Self::StoryManifest => "story_manifest",
        }
    }
}

impl DeltaOperation {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Create => "create",
            Self::Update => "update",
            Self::Upsert => "upsert",
            Self::Delete => "delete",
            Self::Append => "append",
        }
    }
}

impl DeliveryState {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Staged => "staged",
            Self::Ready => "ready",
            Self::Sent => "sent",
            Self::Acked => "acked",
            Self::Conflicted => "conflicted",
            Self::Failed => "failed",
        }
    }
}

impl BindingStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Unlinked => "unlinked",
            Self::Stale => "stale",
        }
    }
}

impl ProfileKind {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::LocalAgent => "local_agent",
            Self::PlatformHosted => "platform_hosted",
        }
    }
}

impl SelectionMode {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Registry => "registry",
            Self::ManualCommand => "manual_command",
            Self::ManualRemote => "manual_remote",
        }
    }
}

impl AgentProfileStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Unavailable => "unavailable",
            Self::Deprecated => "deprecated",
        }
    }
}

impl RuntimeMode {
    /// String representation matching JSON Schema enum values.
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::LocalOnly => "local_only",
            Self::LocalFirst => "local_first",
            Self::CloudEnhanced => "cloud_enhanced",
        }
    }
}

impl ChapterStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::NotStarted => "not_started",
            Self::Outlined => "outlined",
            Self::Draft => "draft",
            Self::Finalized => "finalized",
            Self::Published => "published",
        }
    }
}

// ── as_str() for domain generated enums (plan v1.138 P1) ──────────────────
// Consumers call `.as_str()` on these typify-generated enums at contract↔domain
// conversion boundaries. The serde-rename values mirror the canonical
// `common_types` strings; these impls are kept in lock-step with the schema.
// The first three share names with `common_types` enums imported above, so
// their impls are written against the fully-qualified generated path.

impl crate::generated::domain::key_block::KeyBlockStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Provisional => "provisional",
            Self::Confirmed => "confirmed",
            Self::Deprecated => "deprecated",
            Self::Merged => "merged",
            Self::Deleted => "deleted",
        }
    }
}

impl crate::generated::domain::pairing::PairingStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Revoked => "revoked",
        }
    }
}

impl crate::generated::domain::creator::CreatorStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Archived => "archived",
            Self::Locked => "locked",
        }
    }
}

impl PairingPairingSource {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AutoCli => "auto_cli",
            Self::ManualWeb => "manual_web",
            Self::PlatformAuto => "platform_auto",
        }
    }
}

impl UserAccountStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Suspended => "suspended",
            Self::Deleted => "deleted",
        }
    }
}

impl UserSubscriptionTier {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Free => "free",
            Self::Pro => "pro",
            Self::Studio => "studio",
            Self::Enterprise => "enterprise",
        }
    }
}

impl CreatorRegistrationSource {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Cli => "cli",
            Self::WebAgent => "web_agent",
            Self::Platform => "platform",
        }
    }
}

// ── as_str() for remaining domain generated enums (plan v1.138 P1) ─────────
// Same rationale as above: consumers call `.as_str()` at contract↔domain
// boundaries. All written against fully-qualified generated paths to avoid
// import-name collisions with the `common_types` enums imported at the top.

impl crate::generated::domain::world::WorldStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Paused => "paused",
            Self::Archived => "archived",
        }
    }
}

impl crate::generated::domain::world::WorldTimePolicy {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Manual => "manual",
            Self::OwnerDriven => "owner_driven",
            Self::EventDriven => "event_driven",
        }
    }
}

impl crate::generated::domain::world::WorldVisibility {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Private => "private",
            Self::Unlisted => "unlisted",
            Self::Public => "public",
        }
    }
}

impl crate::generated::domain::world_membership::WorldMembershipRole {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Owner => "owner",
            Self::Maintainer => "maintainer",
            Self::Collaborator => "collaborator",
            Self::OfficialCreator => "official_creator",
        }
    }
}

impl crate::generated::domain::world_membership::WorldMembershipMembershipStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Invited => "invited",
            Self::Suspended => "suspended",
            Self::Removed => "removed",
        }
    }
}

impl crate::generated::domain::timeline_event::TimelineEventStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Canon => "canon",
            Self::Provisional => "provisional",
            Self::Rejected => "rejected",
        }
    }
}

impl crate::generated::domain::timeline_event::TimelineEventEventType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::StoryAdvance => "story_advance",
            Self::StateUpdate => "state_update",
            Self::ForkMarker => "fork_marker",
            Self::OfficialProgression => "official_progression",
            Self::PublishMarker => "publish_marker",
        }
    }
}

impl crate::generated::domain::story_manifest::StoryManifestStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::SummaryReady => "summary_ready",
            Self::StagedForPublish => "staged_for_publish",
            Self::Published => "published",
            Self::Archived => "archived",
        }
    }
}

impl crate::generated::domain::story_manifest::StoryManifestManifestType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Chapter => "chapter",
            Self::Arc => "arc",
            Self::Story => "story",
            Self::Excerpt => "excerpt",
        }
    }
}

impl crate::generated::domain::story_manifest::StoryManifestManuscriptStorage {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::LocalWorkspace => "local_workspace",
            Self::PlatformSandbox => "platform_sandbox",
        }
    }
}

impl crate::generated::domain::memory::MemoryStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Superseded => "superseded",
            Self::Archived => "archived",
        }
    }
}

impl crate::generated::domain::memory::MemoryMemoryKind {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::StorySummary => "story_summary",
            Self::ResearchMaterial => "research_material",
            Self::ReviewNote => "review_note",
            Self::CharacterNote => "character_note",
            Self::WorldBuilding => "world_building",
            Self::PlotOutline => "plot_outline",
            Self::ThemeAnalysis => "theme_analysis",
            Self::PersonalityCore => "personality_core",
            Self::Custom => "custom",
        }
    }
}

impl crate::generated::domain::memory::MemoryMemoryType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Canon => "canon",
            Self::Working => "working",
            Self::Experience => "experience",
        }
    }
}

impl crate::generated::domain::fork_branch::ForkBranchStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Archived => "archived",
        }
    }
}

impl crate::generated::domain::fork_branch::ForkBranchVerificationStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Unverified => "unverified",
            Self::Requested => "requested",
            Self::Verified => "verified",
            Self::Rejected => "rejected",
        }
    }
}

// ── as_str() for compute / sync / bundle generated enums (plan v1.138 P1) ──
impl crate::generated::daemon_api::compute::compute_output::ComputeOutputStateDeltaItemOp {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Add => "+",
            Self::Sub => "-",
            Self::Set => "set",
        }
    }
}

impl crate::generated::platform::sync::bundle::NexusDeltaOperation {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Create => "create",
            Self::Update => "update",
            Self::Upsert => "upsert",
            Self::Delete => "delete",
            Self::Append => "append",
        }
    }
}

impl crate::generated::platform::sync::bundle::NexusDeltaDeltaType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::World => "world",
            Self::KeyBlock => "key_block",
            Self::TimelineEvent => "timeline_event",
            Self::ForkBranch => "fork_branch",
            Self::MemoryItem => "memory_item",
            Self::StoryManifest => "story_manifest",
        }
    }
}

impl crate::generated::platform::sync::sync_command::SyncCommandCommandType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AdvanceWorld => "advance_world",
            Self::InjectFutureEvent => "inject_future_event",
            Self::ExtractKb => "extract_kb",
            Self::SyncPush => "sync_push",
            Self::SyncPull => "sync_pull",
            Self::ForkWorld => "fork_world",
            Self::PublishStory => "publish_story",
        }
    }
}

// ── FromStr implementations ───────────────────────────────────────────────
// Note: typify generates `FromStr` for all schema string enums (plan v1.138 T5).
// Only `RuntimeMode` (a local-only type, NOT typify-generated) retains a
// hand-written `FromStr` here.

impl FromStr for RuntimeMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "local_only" => Ok(Self::LocalOnly),
            "local_first" => Ok(Self::LocalFirst),
            "cloud_enhanced" => Ok(Self::CloudEnhanced),
            _ => Err(format!(
                "unknown runtime mode: '{s}'; expected local_only, local_first, or cloud_enhanced"
            )),
        }
    }
}

// `ReferenceSourceType` / `ScanStatus` are common_types-only (no typify
// counterpart at the crate root) yet consumers parse them from strings when
// rebuilding the local `ReferenceSource` aggregate (plan v1.138 P1).
impl FromStr for ReferenceSourceType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "file" => Ok(Self::File),
            "pdf" => Ok(Self::Pdf),
            "url" => Ok(Self::Url),
            "note" => Ok(Self::Note),
            _ => Err(format!(
                "unknown reference source type: '{s}'; expected file, pdf, url, or note"
            )),
        }
    }
}

impl FromStr for ScanStatus {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "pending" => Ok(Self::Pending),
            "scanned" => Ok(Self::Scanned),
            "failed" => Ok(Self::Failed),
            "ignored" => Ok(Self::Ignored),
            _ => Err(format!(
                "unknown scan status: '{s}'; expected pending, scanned, failed, or ignored"
            )),
        }
    }
}

// ── as_str() for daemon-api request/response enums (plan v1.138 P1) ─────────
// Consumers call `.as_str()` at contract↔domain boundaries. Same pattern as
// the domain enums above: typify emits `Display`+`FromStr` but not `as_str()`.
// All written against fully-qualified generated paths.

impl crate::generated::daemon_api::works::chapters::patch_chapter_request::NexusChapterStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::NotStarted => "not_started",
            Self::Outlined => "outlined",
            Self::Draft => "draft",
            Self::Finalized => "finalized",
            Self::Published => "published",
        }
    }
}

impl crate::generated::daemon_api::works::chapters::list_chapters_query::NexusChapterStatus {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::NotStarted => "not_started",
            Self::Outlined => "outlined",
            Self::Draft => "draft",
            Self::Finalized => "finalized",
            Self::Published => "published",
        }
    }
}

impl crate::generated::daemon_api::canvas::world_kb::world_kb_patch_entity_request::NexusWorldKbEntityPatchBlockType {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Character => "character",
            Self::Ability => "ability",
            Self::Scene => "scene",
            Self::Organization => "organization",
            Self::Item => "item",
            Self::Conflict => "conflict",
            Self::InfoPoint => "info_point",
            Self::Event => "event",
            Self::Species => "species",
            Self::Faction => "faction",
            Self::MagicSystem => "magic_system",
            Self::Technology => "technology",
            Self::Deity => "deity",
            Self::Level => "level",
            Self::EconomyTier => "economy_tier",
            Self::Dialogue => "dialogue",
            Self::Beat => "beat",
            Self::Act => "act",
            Self::Era => "era",
        }
    }
}

impl crate::generated::daemon_api::canvas::world_kb::world_kb_promote_candidate_request::WorldKbPromoteCandidateRequestAction {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Adopt => "adopt",
            Self::Reject => "reject",
            Self::Merge => "merge",
        }
    }
}

impl crate::generated::daemon_api::canvas::world_kb::world_kb_patch_relationship_request::WorldKbPatchRelationshipRequestAction {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Add => "add",
            Self::Update => "update",
            Self::Remove => "remove",
        }
    }
}

impl crate::generated::daemon_api::canvas::world_kb::world_kb_relationship_input::NexusWorldKbRelationshipKind {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AlliedWith => "allied_with",
            Self::Opposes => "opposes",
            Self::ParentOf => "parent_of",
            Self::ChildOf => "child_of",
            Self::MemberOf => "member_of",
            Self::LocatedIn => "located_in",
            Self::RulesOver => "rules_over",
            Self::References => "references",
            Self::Serves => "serves",
            Self::RivalOf => "rival_of",
            Self::MentorOf => "mentor_of",
            Self::Custom => "custom",
        }
    }
}

impl crate::generated::daemon_api::canvas::world_kb::world_kb_patch_relationship_request::NexusWorldKbRelationshipKind {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AlliedWith => "allied_with",
            Self::Opposes => "opposes",
            Self::ParentOf => "parent_of",
            Self::ChildOf => "child_of",
            Self::MemberOf => "member_of",
            Self::LocatedIn => "located_in",
            Self::RulesOver => "rules_over",
            Self::References => "references",
            Self::Serves => "serves",
            Self::RivalOf => "rival_of",
            Self::MentorOf => "mentor_of",
            Self::Custom => "custom",
        }
    }
}

impl crate::generated::daemon_api::canvas::outline::outline_patch_structure_request::OutlinePatchStructureRequestOperation {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::MoveChapter => "move_chapter",
            Self::LinkEvent => "link_event",
            Self::AttachToVolume => "attach_to_volume",
        }
    }
}

impl crate::generated::daemon_api::canvas::outline::timeline_patch_event_request::TimelinePatchEventRequestOperation {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::AddEvent => "add_event",
            Self::RemoveEvent => "remove_event",
            Self::AttachEventToChapter => "attach_event_to_chapter",
            Self::LinkForeshadow => "link_foreshadow",
            Self::UnlinkForeshadow => "unlink_foreshadow",
        }
    }
}

// ── as_str() for strategy patch request enums (plan v1.138 P1) ─────────────
impl crate::generated::daemon_api::canvas::strategy::strategy_patch_transition_request::StrategyPatchTransitionRequestTransitionKind {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Next => "next",
            Self::Branch => "branch",
            Self::Default => "default",
        }
    }
}

impl crate::generated::daemon_api::canvas::strategy::strategy_patch_transition_request::StrategyPatchTransitionRequestOp {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Create => "create",
            Self::Update => "update",
        }
    }
}

// `DeliveryState` is common_types-only (the outbox stores it as a stringified
// enum column) and consumers rebuild it from strings.
impl FromStr for DeliveryState {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "staged" => Ok(Self::Staged),
            "ready" => Ok(Self::Ready),
            "sent" => Ok(Self::Sent),
            "acked" => Ok(Self::Acked),
            "conflicted" => Ok(Self::Conflicted),
            "failed" => Ok(Self::Failed),
            _ => Err(format!(
                "unknown delivery state: '{s}'; expected staged, ready, sent, acked, conflicted, or failed"
            )),
        }
    }
}
