//! Build script that generates a compile-time list of embedded preset IDs
//! by scanning the nexus-orchestration embedded-presets directory.
//!
//! This allows `preset list` to show embedded presets without requiring
//! the daemon to be running (R-M1-W03).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let embedded_dir = Path::new(&manifest_dir)
        .join("..")
        .join("nexus-orchestration")
        .join("embedded-presets");

    // Collect directory names that contain a preset.yaml.
    let mut preset_ids: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&embedded_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() && path.join("preset.yaml").exists() {
                if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                    preset_ids.push(name.to_string());
                }
            }
        }
    }

    // Sort for deterministic output.
    preset_ids.sort();

    // Generate the const array.
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest_path = Path::new(&out_dir).join("embedded_preset_ids.rs");

    let mut code = String::from("/// Embedded preset IDs generated at compile time from\n/// `crates/nexus-orchestration/embedded-presets/`.\n///\n/// DO NOT EDIT — generated by build.rs.\n#[rustfmt::skip]\npub const EMBEDDED_PRESET_IDS: &[&str] = &[\n");
    for id in &preset_ids {
        use std::fmt::Write;
        writeln!(code, "    \"{id}\",").unwrap();
    }
    code.push_str("];\n");

    fs::write(&dest_path, code).expect("failed to write embedded_preset_ids.rs");

    // Rerun if the embedded presets directory changes.
    println!("cargo:rerun-if-changed=../nexus-orchestration/embedded-presets");
}
