// Generated by @nexus/design-tokens — DERIVED OUTPUT, do not edit by hand.
// Light/default numeric snapshot from repo-root DESIGN.md §Brand Colors.
// Theme-aware UI reads CSS (--nexus-brand-* / --color-brand-*) rather than
// these constants. `cyan` is the historical property name for the
// recalibrated cobalt signal. Regenerate: pnpm --filter @nexus/design-tokens generate.
export const brandColors = {
  deepBlue: '#202936' as const,
  cyan: '#3263C7' as const,
  white: '#FFFFFF' as const,
} as const;
