//! Build script that generates a compile-time list of embedded preset IDs
//! by scanning the nexus-orchestration embedded-presets directory.
//!
//! This supports command surfaces that need embedded preset IDs without
//! requiring the daemon to be running (R-M1-W03).
//!
//! ## Cross-crate build-time dependency (QC1 W-A02)
//!
//! **What it reads:** Embedded preset IDs from `crates/nexus-orchestration/embedded-presets/`.
//! Each subdirectory containing a `preset.yaml` file is treated as a preset whose ID
//! is the directory name.
//!
//! **Why:** CLI/API presentation code may need to display embedded presets without
//! connecting to the daemon. Reading at compile time avoids a runtime dependency
//! on nexus-orchestration's `include_dir!` from the CLI binary.
//!
//! **Contract:**
//! - Expects a flat directory of subdirectories under `embedded-presets/`.
//! - Each subdirectory must contain a `preset.yaml` file with an `id:` field.
//! - Directory names are sorted for deterministic output.
//!
//! **What breaks if the contract changes:** If the directory structure or naming
//! convention changes in nexus-orchestration, this build script will either
//! produce incorrect preset IDs or the compile will fail if the directory
//! is missing. Changes to `embedded-presets/` layout must be coordinated
//! with this build script.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let embedded_dir = Path::new(&manifest_dir)
        .join("..")
        .join("..")
        .join("crates")
        .join("nexus-orchestration")
        .join("embedded-presets");

    // Collect directory names that contain a preset.yaml.
    let mut preset_ids: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&embedded_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() && path.join("preset.yaml").exists() {
                if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                    preset_ids.push(name.to_string());
                }
            }
        }
    }

    // Sort for deterministic output.
    preset_ids.sort();

    // Generate the const array.
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest_path = Path::new(&out_dir).join("embedded_preset_ids.rs");

    let mut code = String::from("/// Embedded preset IDs generated at compile time from\n/// `crates/nexus-orchestration/embedded-presets/`.\n///\n/// DO NOT EDIT — generated by build.rs.\n#[rustfmt::skip]\npub const EMBEDDED_PRESET_IDS: &[&str] = &[\n");
    for id in &preset_ids {
        use std::fmt::Write;
        writeln!(code, "    \"{id}\",").unwrap();
    }
    code.push_str("];\n");

    fs::write(&dest_path, code).expect("failed to write embedded_preset_ids.rs");

    // Rerun if the embedded presets directory changes.
    println!("cargo:rerun-if-changed=../../crates/nexus-orchestration/embedded-presets");

    // V1.154 P2 T1: probe whether the wasm32-unknown-unknown target is
    // installed so the Connect compute interop tests (which install the
    // embedded `basic-combat` module into a hermetic `~/.nexus42/modules/`)
    // can be gated. Mirrors the probes in `nexus-wasm-host/build.rs` and
    // `nexus-spoke-adapter/build.rs` — the upstream cfg is per-crate and
    // does not propagate to dependents.
    println!("cargo::rustc-check-cfg=cfg(nexus42_no_wasm_target)");
    if !has_wasm_target() {
        println!(
            "cargo:warning=nexus42: wasm32-unknown-unknown target not found; \
             skipping embedded-module compute interop tests. Install the target with: \
             rustup target add wasm32-unknown-unknown"
        );
        println!("cargo:rustc-cfg=nexus42_no_wasm_target");
    }
}

/// Returns `true` when the `wasm32-unknown-unknown` sysroot is installed.
///
/// Uses `rustc --print sysroot --target wasm32-unknown-unknown` which exits 0
/// only when the target is available. This is a fast metadata query — it does
/// not compile anything.
#[must_use]
fn has_wasm_target() -> bool {
    std::process::Command::new("rustc")
        .args(["--print", "sysroot", "--target", "wasm32-unknown-unknown"])
        .output()
        .is_ok_and(|o| o.status.success())
}
