//! Worker Manager — spawn, supervise, and shut down worker child processes.
//!
//! Architecture:
//! - `WorkerManager` spawns child processes and tracks them.
//! - `WorkerHandle` provides IPC via [`IpcClient`] and shutdown.
//! - A background supervisor task per worker calls `child.wait()` and
//!   emits `WorkerEvent::Crashed` on unexpected exit.
//!
//! The `Child` is moved into the supervisor task. The handle holds the
//! `IpcClient` (wrapping stdin/stdout), the PID, and a
//! `CancellationToken` for in-flight request cancellation.
//!
//! ## WS2 R4: SIGTERM → SIGKILL escalation
//!
//! On shutdown, the supervisor sends SIGTERM first, waits for the grace period
//! from `shutdown_grace`, then escalates to SIGKILL if the worker hasn't exited.
//! This follows the graceful shutdown pattern from §6.5 of the design spec.
//!
//! ## WS-E T1: Persistent IpcClient
//!
//! `WorkerHandle` now holds an [`IpcClient`] internally. The legacy
//! `call_json_rpc` method is preserved for backward compatibility — it
//! delegates to the internal `IpcClient`.
//!
//! Design: `.agents/plans/knowledge/orchestration-engine-v1.md` §6.1, §6.5.

use crate::worker::ipc::IpcClient;
use crate::worker::transport::StdioTransport;
use nix::sys::signal::{kill, Signal};
use nix::unistd::Pid;
use serde_json::Value;
use std::time::Duration;
use thiserror::Error;
use tokio::process::Command;
use tokio::sync::broadcast;
use tokio_util::sync::CancellationToken;
use tracing::{debug, error, info, warn};

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Errors from worker management operations.
#[derive(Error, Debug)]
pub enum WorkerError {
    #[error("failed to spawn worker: {0}")]
    SpawnFailed(std::io::Error),
    #[error("IPC error: {0}")]
    Ipc(String),
    #[error("worker crashed with exit status: {0}")]
    Crashed(String),
    #[error("shutdown timeout — worker did not exit within grace period")]
    ShutdownTimeout,
    #[error("worker not running")]
    NotRunning,
    #[error("internal: {0}")]
    Internal(String),
}

// ---------------------------------------------------------------------------
// WorkerAgentConfig
// ---------------------------------------------------------------------------

/// Configuration for one agent slot within a multi-agent worker.
///
/// Used by the daemon to construct the `worker/initialize` payload with
/// `acp_agent_id` / `role` / `model` separation (WS-E §7.2).
///
/// This is the **runtime type** assembled by the daemon from preset roles +
/// user config + CLI flags, not a user-facing config file type.
///
/// ## T8: System Prompt Injection
///
/// `system_prompt` contains the role's system prompt content (read by daemon
/// from `system_prompt_file` in the preset). It is sent via IPC to the worker,
/// which injects it as the first message when creating the ACP session.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct WorkerAgentConfig {
    /// Unique session ID for this agent slot (runtime-generated by daemon).
    pub session_id: String,

    /// Which ACP agent to launch — references an agent ID from the ACP Registry.
    /// Example: "claude-acp", "codex-acp", "gemini".
    pub acp_agent_id: String,

    /// Which role/persona to use when starting the ACP session.
    /// References a role defined in the preset's `roles` section.
    pub role: Option<String>,

    /// Which LLM model to use.
    /// Example: "claude-sonnet-4-20250514", "o3", "gemini-2.5-pro".
    pub model: Option<String>,

    /// Optional ACP session ID to resume (session/load).
    pub acp_session_id: Option<String>,

    /// Tool policy override for this agent slot.
    pub tool_policy: Option<String>,

    /// System prompt content for the role (T8).
    /// Daemon reads from role's `system_prompt_file` in the preset and sends
    /// via IPC. Worker injects as first message when creating ACP session.
    /// Missing/invalid file = None (graceful handling, no error).
    pub system_prompt: Option<String>,
}

impl WorkerAgentConfig {
    /// Create a minimal config with required fields.
    pub fn new(session_id: String, acp_agent_id: String) -> Self {
        Self {
            session_id,
            acp_agent_id,
            role: None,
            model: None,
            acp_session_id: None,
            tool_policy: None,
            system_prompt: None,
        }
    }

    /// Builder-style role assignment.
    pub fn with_role(mut self, role: String) -> Self {
        self.role = Some(role);
        self
    }

    /// Builder-style model override.
    pub fn with_model(mut self, model: String) -> Self {
        self.model = Some(model);
        self
    }

    /// Builder-style ACP session ID for resume.
    pub fn with_acp_session_id(mut self, acp_session_id: String) -> Self {
        self.acp_session_id = Some(acp_session_id);
        self
    }

    /// Builder-style tool policy override.
    pub fn with_tool_policy(mut self, tool_policy: String) -> Self {
        self.tool_policy = Some(tool_policy);
        self
    }

    /// Builder-style system prompt (T8).
    /// Daemon reads from preset's `system_prompt_file` and passes here.
    pub fn with_system_prompt(mut self, system_prompt: String) -> Self {
        self.system_prompt = Some(system_prompt);
        self
    }

    /// Format this config as a `--agent-ref` CLI argument.
    ///
    /// Format: `role:acp_agent_id[:model]` (matches WS-E §7.6).
    /// If `role` is absent, uses the session_id as the key prefix.
    pub fn to_agent_ref_arg(&self) -> String {
        let role_key = self.role.as_ref().unwrap_or(&self.session_id);
        let mut parts = vec![role_key.clone(), self.acp_agent_id.clone()];
        if let Some(model) = &self.model {
            parts.push(model.clone());
        }
        parts.join(":")
    }
}

// ---------------------------------------------------------------------------
// WorkerSpec
// ---------------------------------------------------------------------------

/// Describes how to launch a worker process.
///
/// Extended in WS-E T4 to support multi-agent configuration:
/// - `creator_id` — used for `WorkerRegistry` indexing.
/// - `agents` — list of `WorkerAgentConfig` for multi-agent workers.
///
/// Backward compatibility: existing code that creates `WorkerSpec` without
/// these fields still compiles (using `Default::default()` or builder pattern).
#[derive(Debug, Clone, Default)]
pub struct WorkerSpec {
    /// Path to the worker binary or script.
    pub program: String,
    /// Arguments passed to the worker program.
    pub args: Vec<String>,
    /// Environment variables set for the worker process.
    pub env: Vec<(String, String)>,
    /// Current working directory for the worker.
    pub working_dir: Option<String>,
    /// Creator ID for `WorkerRegistry` indexing (WS-E T4).
    pub creator_id: String,
    /// Multi-agent configuration for this worker (WS-E T4).
    pub agents: Vec<WorkerAgentConfig>,
}

impl WorkerSpec {
    /// Create a spec from a program path (no extra args).
    ///
    /// Backward-compatible: sets `creator_id` and `agents` to defaults.
    pub fn from_program(program: impl Into<String>) -> Self {
        Self {
            program: program.into(),
            args: Vec::new(),
            env: Vec::new(),
            working_dir: None,
            creator_id: String::new(),
            agents: Vec::new(),
        }
    }

    /// Test helper — creates a spec for a shell script at the given path.
    pub fn test_stub(path: &str) -> Self {
        Self::from_program("bash").with_arg(path)
    }

    /// Add an argument.
    pub fn with_arg(mut self, arg: impl Into<String>) -> Self {
        self.args.push(arg.into());
        self
    }

    /// Add an environment variable.
    pub fn with_env(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.env.push((key.into(), value.into()));
        self
    }

    /// Add a working directory.
    pub fn with_working_dir(mut self, dir: impl Into<String>) -> Self {
        self.working_dir = Some(dir.into());
        self
    }

    /// Set the creator ID for registry indexing (WS-E T4).
    pub fn with_creator_id(mut self, creator_id: impl Into<String>) -> Self {
        self.creator_id = creator_id.into();
        self
    }

    /// Set the agents list for multi-agent workers (WS-E T4).
    pub fn with_agents(mut self, agents: Vec<WorkerAgentConfig>) -> Self {
        self.agents = agents;
        self
    }

    /// Add a single agent config (builder-style, WS-E T4).
    pub fn with_agent(mut self, agent: WorkerAgentConfig) -> Self {
        self.agents.push(agent);
        self
    }

    /// Build `--agent-ref` CLI arguments from the agents list.
    ///
    /// For each agent in `self.agents`, generates a `--agent-ref` argument
    /// in the format `role:acp_agent_id[:model]` (WS-E §7.6).
    ///
    /// Returns an empty vector if `self.agents` is empty.
    pub fn build_agent_ref_args(&self) -> Vec<String> {
        self.agents.iter().map(|a| a.to_agent_ref_arg()).collect()
    }
}

// ---------------------------------------------------------------------------
// WorkerEvent
// ---------------------------------------------------------------------------

/// Events emitted by the worker manager about worker state changes.
#[derive(Debug, Clone)]
pub enum WorkerEvent {
    /// Worker process exited unexpectedly.
    Crashed { pid: u32, exit_status: Option<i32> },
    /// Worker started successfully.
    Started { pid: u32 },
    /// Worker was gracefully shut down.
    Stopped { pid: u32 },
    /// An agent session within a worker reported a state change.
    ///
    /// Emitted when the worker sends a `worker/agent_session_event`
    /// notification (e.g., `"started"`, `"stopped"`, `"crashed"`).
    /// The daemon uses this to track per-session health and trigger
    /// crash recovery for individual agents without affecting others.
    AgentSessionEvent {
        /// Worker PID that owns the session.
        pid: u32,
        /// Session identifier within the worker.
        session_id: String,
        /// Event type: `"started"`, `"stopped"`, `"crashed"`.
        event: String,
        /// Human-readable reason (present for `"crashed"` events).
        reason: Option<String>,
    },
}

// ---------------------------------------------------------------------------
// WorkerHandle
// ---------------------------------------------------------------------------

/// Handle to a running worker process.
///
/// Owns an [`IpcClient`] for multiplexed IPC and a cancellation token.
/// The `Child` itself is owned by a background supervisor task.
///
/// ## Backward compatibility
///
/// The legacy `call_json_rpc` method is preserved — it delegates to the
/// internal `IpcClient::call`. New code should prefer using
/// [`WorkerHandle::ipc_client`] directly for concurrent requests.
pub struct WorkerHandle {
    /// PID of the worker process.
    pid: u32,
    /// Cancellation token — fires on shutdown or crash.
    cancel: CancellationToken,
    /// Broadcast sender for events (used by IpcClient for notification routing in WS3).
    #[allow(dead_code)]
    event_tx: broadcast::Sender<WorkerEvent>,
    /// Grace period for shutdown (default: 30 seconds, configurable via spec).
    shutdown_grace: Duration,
    /// Persistent IpcClient for multiplexed JSON-RPC communication.
    ipc: IpcClient,
    /// Whether a clean shutdown has been requested.
    shutdown_requested: bool,
}

impl WorkerHandle {
    /// Create a `WorkerHandle` from an [`IpcClient`] for testing.
    ///
    /// Uses PID 0 (sentinel for mock workers), a fresh cancellation token,
    /// and a no-op broadcast channel. The shutdown grace period is set to
    /// 1 second to keep tests fast.
    /// Create a `WorkerHandle` from an [`IpcClient`] for testing.
    ///
    /// Uses PID 0 (sentinel for mock workers), a fresh cancellation token,
    /// and a no-op broadcast channel. The shutdown grace period is set to
    /// 1 second to keep tests fast.
    ///
    /// This is only intended for integration tests; production code should
    /// obtain handles via [`WorkerManager::spawn`].
    pub fn from_ipc_for_test(ipc: IpcClient) -> Self {
        let (event_tx, _) = broadcast::channel(1);
        Self {
            pid: 0,
            cancel: CancellationToken::new(),
            event_tx,
            shutdown_grace: Duration::from_secs(1),
            ipc,
            shutdown_requested: false,
        }
    }

    /// Send a JSON-RPC request to the worker and await the response.
    ///
    /// Delegates to the internal [`IpcClient`]. This method can be called
    /// multiple times — the underlying `IpcClient` supports concurrent
    /// in-flight requests.
    ///
    /// For concurrent requests, prefer [`WorkerHandle::ipc_client`] which
    /// returns `&IpcClient` for direct use with multiple outstanding calls.
    pub async fn call_json_rpc(&self, method: &str, params: Value) -> Result<Value, WorkerError> {
        self.ipc
            .call(method, params)
            .await
            .map_err(|e| WorkerError::Ipc(e.to_string()))
    }

    /// Request a graceful shutdown of the worker.
    ///
    /// Sends a `worker/shutdown` JSON-RPC request and fires the cancellation
    /// token. The supervisor task will send SIGTERM first, wait for the grace
    /// period, then SIGKILL if needed (WS2 R4).
    pub async fn shutdown(&mut self) -> Result<(), WorkerError> {
        self.shutdown_requested = true;
        self.cancel.cancel();

        info!(
            pid = self.pid,
            grace_ms = self.shutdown_grace.as_millis(),
            "requesting worker shutdown via cancellation token"
        );

        // Try to send a shutdown RPC via IpcClient.
        if !self.ipc.is_closed() {
            let grace_ms = self.shutdown_grace.as_millis() as u32;
            match self
                .ipc
                .call("worker/shutdown", serde_json::json!({"grace_ms": grace_ms}))
                .await
            {
                Ok(_) => {
                    info!(pid = self.pid, "worker acknowledged shutdown RPC");
                }
                Err(e) => {
                    // Worker may have already exited — this is fine.
                    warn!(pid = self.pid, error = %e, "shutdown RPC failed (worker may have already exited)");
                }
            }
        } else {
            info!(
                pid = self.pid,
                "IPC client already closed — supervisor will send SIGTERM"
            );
        }

        // Close the IpcClient to clean up the background reader.
        self.ipc.close().await;

        Ok(())
    }

    /// Return a reference to the internal [`IpcClient`].
    ///
    /// Use this for concurrent multiplexed requests — multiple callers can
    /// call [`IpcClient::call`] on the returned reference simultaneously.
    pub fn ipc_client(&self) -> &IpcClient {
        &self.ipc
    }

    /// Return the process ID.
    pub fn pid(&self) -> u32 {
        self.pid
    }

    /// Return a reference to the cancellation token.
    pub fn cancel_token(&self) -> CancellationToken {
        self.cancel.clone()
    }

    /// Return the configured shutdown grace period.
    pub fn shutdown_grace(&self) -> Duration {
        self.shutdown_grace
    }

    // ---------------------------------------------------------------------------
    // WS-E T4: Multi-agent IPC methods
    // ---------------------------------------------------------------------------

    /// Start a new agent session in this worker.
    ///
    /// Sends `worker/agent_start` IPC method to the worker process.
    /// Returns a summary of the newly created agent session.
    ///
    /// # Arguments
    ///
    /// * `config` — agent configuration to pass to the worker.
    ///
    /// # Errors
    ///
    /// Returns `WorkerError::Ipc` if the session already exists or the worker
    /// fails to start the agent.
    ///
    /// # T8: System Prompt
    ///
    /// If `config.system_prompt` is set, it is sent via IPC and injected
    /// as the first message when the worker creates the ACP session.
    pub async fn agent_start(
        &self,
        config: &WorkerAgentConfig,
    ) -> Result<AgentSessionSummary, WorkerError> {
        let params = serde_json::json!({
            "session_id": config.session_id,
            "acp_agent_id": config.acp_agent_id,
            "role": config.role,
            "model": config.model,
            // T8: system_prompt (daemon reads from preset, worker injects)
            "system_prompt": config.system_prompt,
        });

        let response = self.call_json_rpc("worker/agent_start", params).await?;

        // Parse the response: { "session": { ... } }
        let session_obj = response.get("session").cloned().ok_or_else(|| {
            WorkerError::Ipc("agent_start response missing 'session' field".to_string())
        })?;

        let summary: AgentSessionSummary = serde_json::from_value(session_obj)
            .map_err(|e| WorkerError::Ipc(format!("failed to parse agent_start response: {e}")))?;

        Ok(summary)
    }

    /// Stop an agent session in this worker.
    ///
    /// Sends `worker/agent_stop` IPC method to the worker process.
    /// The agent subprocess is terminated and the session slot is removed.
    ///
    /// # Arguments
    ///
    /// * `session_id` — which session to stop.
    /// * `grace_ms` — grace period for agent subprocess shutdown.
    ///
    /// # Errors
    ///
    /// Returns `WorkerError::Ipc` if the session does not exist.
    pub async fn agent_stop(&self, session_id: &str, grace_ms: u32) -> Result<(), WorkerError> {
        let params = serde_json::json!({
            "session_id": session_id,
            "grace_ms": grace_ms,
        });

        self.call_json_rpc("worker/agent_stop", params).await?;

        Ok(())
    }

    /// List all active agent sessions in this worker.
    ///
    /// Sends `worker/agent_list` IPC method to the worker process.
    /// Returns summaries of all currently active agent sessions.
    ///
    /// # Errors
    ///
    /// Returns `WorkerError::Ipc` on IPC failure.
    pub async fn agent_list(&self) -> Result<Vec<AgentSessionSummary>, WorkerError> {
        let response = self
            .call_json_rpc("worker/agent_list", serde_json::json!({}))
            .await?;

        // Parse the response: { "sessions": [...] }
        let sessions_value = response.get("sessions").cloned().ok_or_else(|| {
            WorkerError::Ipc("agent_list response missing 'sessions' field".to_string())
        })?;

        let summaries: Vec<AgentSessionSummary> = serde_json::from_value(sessions_value)
            .map_err(|e| WorkerError::Ipc(format!("failed to parse agent_list response: {e}")))?;

        Ok(summaries)
    }
}

// ---------------------------------------------------------------------------
// AgentSessionSummary — IPC response type
// ---------------------------------------------------------------------------

/// Summary of an agent session, returned by `worker/agent_list` and `worker/agent_start`.
///
/// Matches the worker-side `session_summary_json` output from WS-E T3.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AgentSessionSummary {
    /// Session identifier within the worker.
    pub session_id: String,
    /// ACP agent ID (from ACP Registry).
    pub acp_agent_id: String,
    /// Role/persona assignment (optional).
    pub role: Option<String>,
    /// Model override (optional).
    pub model: Option<String>,
    /// Current state: "initializing", "ready", "prompting", "error", "stopping", "stopped".
    pub state: String,
    /// Milliseconds since session creation.
    pub uptime_ms: u64,
}

impl AgentSessionSummary {
    /// Check if this session is in a ready state.
    pub fn is_ready(&self) -> bool {
        self.state == "ready"
    }

    /// Check if this session is in an error state.
    pub fn is_error(&self) -> bool {
        self.state == "error"
    }
}

impl Drop for WorkerHandle {
    fn drop(&mut self) {
        if !self.shutdown_requested {
            debug!(
                pid = self.pid,
                "WorkerHandle dropped without explicit shutdown — cancelling"
            );
            self.cancel.cancel();
        }
    }
}

// ---------------------------------------------------------------------------
// WorkerManager
// ---------------------------------------------------------------------------

/// Manages the lifecycle of worker child processes.
///
/// Each spawned worker gets a background supervisor task that monitors its
/// exit status. If the worker exits unexpectedly (non-zero or before a
/// clean shutdown), a `WorkerEvent::Crashed` is emitted.
pub struct WorkerManager {
    /// Broadcast channel for worker lifecycle events.
    event_tx: broadcast::Sender<WorkerEvent>,
}

impl WorkerManager {
    /// Create a new worker manager.
    pub fn new() -> Self {
        let (event_tx, _) = broadcast::channel(64);
        Self { event_tx }
    }

    /// Spawn a new worker process from the given spec.
    ///
    /// Returns a [`WorkerHandle`] for IPC and lifecycle management.
    /// A background supervisor task monitors the child process and emits
    /// events via the manager's broadcast channel.
    pub async fn spawn(&self, spec: &WorkerSpec) -> Result<WorkerHandle, WorkerError> {
        self.spawn_with_grace(spec, Duration::from_secs(30)).await
    }

    /// Spawn a new worker process with a custom shutdown grace period.
    ///
    /// WS2 R4: The grace period controls how long the supervisor waits
    /// after SIGTERM before escalating to SIGKILL.
    pub async fn spawn_with_grace(
        &self,
        spec: &WorkerSpec,
        shutdown_grace: Duration,
    ) -> Result<WorkerHandle, WorkerError> {
        let mut cmd = Command::new(&spec.program);
        cmd.args(&spec.args)
            .envs(spec.env.iter().cloned())
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::inherit());

        if let Some(dir) = &spec.working_dir {
            cmd.current_dir(dir);
        }

        let mut child = cmd.spawn().map_err(WorkerError::SpawnFailed)?;
        let pid = child.id().unwrap_or(0);

        info!(pid, program = %spec.program, "spawned worker");

        // Take stdin/stdout BEFORE moving the child into the supervisor.
        let stdin = child
            .stdin
            .take()
            .ok_or_else(|| WorkerError::Internal("failed to capture child stdin".to_string()))?;
        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| WorkerError::Internal("failed to capture child stdout".to_string()))?;

        // Create persistent IpcClient from the transport.
        let transport = StdioTransport::new(stdin, stdout);
        let ipc = IpcClient::new(Box::new(transport));

        let cancel = CancellationToken::new();
        let supervisor_cancel = cancel.clone();
        let event_tx = self.event_tx.clone();

        // WS2 R4: Pass grace period to supervisor for SIGTERM→SIGKILL sequence.
        let grace = shutdown_grace;

        // Spawn the supervisor task that waits for child exit.
        tokio::spawn(async move {
            tokio::select! {
                _ = supervisor_cancel.cancelled() => {
                    // WS2 R4: SIGTERM → SIGKILL escalation.
                    // 1. Send SIGTERM first.
                    let nix_pid = Pid::from_raw(pid as i32);
                    if let Err(e) = kill(nix_pid, Signal::SIGTERM) {
                        warn!(pid, error = %e, "failed to send SIGTERM to worker");
                        // If SIGTERM fails, fall back to SIGKILL immediately.
                        let _ = child.start_kill();
                    } else {
                        debug!(pid, grace_ms = grace.as_millis(), "sent SIGTERM, waiting for graceful exit");
                    }

                    // 2. Wait for grace period for clean exit.
                    match tokio::time::timeout(grace, child.wait()).await {
                        Ok(Ok(status)) => {
                            if status.success() {
                                debug!(pid, "worker exited cleanly after SIGTERM");
                                let _ = event_tx.send(WorkerEvent::Stopped { pid });
                            } else {
                                warn!(pid, code = ?status.code(), "worker exited with non-zero status after SIGTERM");
                                let _ = event_tx.send(WorkerEvent::Crashed {
                                    pid,
                                    exit_status: status.code(),
                                });
                            }
                        }
                        Ok(Err(e)) => {
                            warn!(pid, error = %e, "error waiting for worker after SIGTERM");
                            let _ = event_tx.send(WorkerEvent::Crashed {
                                pid,
                                exit_status: None,
                            });
                        }
                        Err(_) => {
                            // 3. Grace period expired — escalate to SIGKILL.
                            warn!(pid, "worker did not exit within grace period, sending SIGKILL");
                            let _ = child.start_kill();
                            let _ = child.wait().await;
                            let _ = event_tx.send(WorkerEvent::Crashed {
                                pid,
                                exit_status: None,
                            });
                        }
                    }
                }
                result = child.wait() => {
                    match result {
                        Ok(status) => {
                            if !status.success() {
                                warn!(
                                    pid,
                                    code = ?status.code(),
                                    "worker process exited with non-zero status"
                                );
                                let _ = event_tx.send(WorkerEvent::Crashed {
                                    pid,
                                    exit_status: status.code(),
                                });
                            } else {
                                // Clean exit (exit 0) — likely from a test script.
                                debug!(pid, "worker exited with status 0");
                                let _ = event_tx.send(WorkerEvent::Stopped { pid });
                            }
                        }
                        Err(e) => {
                            error!(pid, error = %e, "error waiting for worker");
                            let _ = event_tx.send(WorkerEvent::Crashed {
                                pid,
                                exit_status: None,
                            });
                        }
                    }
                }
            }
        });

        let handle = WorkerHandle {
            pid,
            cancel,
            event_tx: self.event_tx.clone(),
            shutdown_grace,
            ipc,
            shutdown_requested: false,
        };

        let _ = self.event_tx.send(WorkerEvent::Started { pid });

        Ok(handle)
    }

    /// Subscribe to worker lifecycle events.
    pub fn subscribe(&self) -> broadcast::Receiver<WorkerEvent> {
        self.event_tx.subscribe()
    }
}

impl Default for WorkerManager {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // --- WorkerAgentConfig tests ---

    #[test]
    fn agent_config_minimal() {
        let config = WorkerAgentConfig::new("s1".to_string(), "claude-acp".to_string());
        assert_eq!(config.session_id, "s1");
        assert_eq!(config.acp_agent_id, "claude-acp");
        assert!(config.role.is_none());
        assert!(config.model.is_none());
        assert!(config.acp_session_id.is_none());
        assert!(config.tool_policy.is_none());
        // T8: system_prompt defaults to None
        assert!(config.system_prompt.is_none());
    }

    #[test]
    fn agent_config_builder() {
        let config = WorkerAgentConfig::new("s1".to_string(), "claude-acp".to_string())
            .with_role("writer".to_string())
            .with_model("claude-sonnet-4".to_string())
            .with_acp_session_id("acp-123".to_string())
            .with_tool_policy("auto_grant".to_string())
            .with_system_prompt("You are a creative writer.".to_string());

        assert_eq!(config.role, Some("writer".to_string()));
        assert_eq!(config.model, Some("claude-sonnet-4".to_string()));
        assert_eq!(config.acp_session_id, Some("acp-123".to_string()));
        assert_eq!(config.tool_policy, Some("auto_grant".to_string()));
        // T8: system_prompt via builder
        assert_eq!(
            config.system_prompt,
            Some("You are a creative writer.".to_string())
        );
    }

    #[test]
    fn agent_config_to_agent_ref_arg_with_role_and_model() {
        let config = WorkerAgentConfig::new("s1".to_string(), "claude-acp".to_string())
            .with_role("writer".to_string())
            .with_model("claude-sonnet-4".to_string());

        let arg = config.to_agent_ref_arg();
        assert_eq!(arg, "writer:claude-acp:claude-sonnet-4");
    }

    #[test]
    fn agent_config_to_agent_ref_arg_with_role_no_model() {
        let config = WorkerAgentConfig::new("s1".to_string(), "claude-acp".to_string())
            .with_role("editor".to_string());

        let arg = config.to_agent_ref_arg();
        assert_eq!(arg, "editor:claude-acp");
    }

    #[test]
    fn agent_config_to_agent_ref_arg_no_role_no_model() {
        let config = WorkerAgentConfig::new("s1".to_string(), "claude-acp".to_string());

        // When no role, uses session_id as key.
        let arg = config.to_agent_ref_arg();
        assert_eq!(arg, "s1:claude-acp");
    }

    #[test]
    fn agent_config_serialization() {
        let config = WorkerAgentConfig::new("s1".to_string(), "claude-acp".to_string())
            .with_role("writer".to_string())
            .with_model("claude-sonnet-4".to_string())
            .with_system_prompt("You are a creative writer.".to_string());

        let json = serde_json::to_string(&config).expect("serialize");
        assert!(json.contains("session_id"));
        assert!(json.contains("claude-acp"));
        assert!(json.contains("writer"));
        // T8: system_prompt serialized
        assert!(json.contains("You are a creative writer"));

        let parsed: WorkerAgentConfig = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(parsed.session_id, config.session_id);
        assert_eq!(parsed.acp_agent_id, config.acp_agent_id);
        // T8: verify roundtrip
        assert_eq!(parsed.system_prompt, config.system_prompt);
    }

    #[test]
    fn agent_config_serialization_without_system_prompt() {
        // T8: verify serialization works when system_prompt is None
        let config = WorkerAgentConfig::new("s2".to_string(), "codex-acp".to_string())
            .with_role("reviewer".to_string());

        let json = serde_json::to_string(&config).expect("serialize");
        // Should serialize null for system_prompt (or skip if skip_serializing_if used)
        // Default behavior: null is serialized
        let parsed: WorkerAgentConfig = serde_json::from_str(&json).expect("deserialize");
        assert!(parsed.system_prompt.is_none());
    }

    #[test]
    fn agent_config_default() {
        let config = WorkerAgentConfig::default();
        assert!(config.session_id.is_empty());
        assert!(config.acp_agent_id.is_empty());
        // T8: system_prompt defaults to None
        assert!(config.system_prompt.is_none());
    }

    // --- T8: Tests for system_prompt in WorkerAgentConfig ---

    #[test]
    fn agent_config_with_system_prompt_builder() {
        let config = WorkerAgentConfig::new("sp_test".to_string(), "gemini".to_string())
            .with_role("researcher".to_string())
            .with_system_prompt("You are a research assistant.".to_string());

        assert_eq!(config.role, Some("researcher".to_string()));
        assert_eq!(
            config.system_prompt,
            Some("You are a research assistant.".to_string())
        );
    }

    #[test]
    fn agent_config_missing_system_prompt_graceful() {
        // T8: verify that missing system_prompt (None) is handled gracefully
        let config = WorkerAgentConfig::new("no_sp".to_string(), "claude-acp".to_string())
            .with_role("editor".to_string());

        assert!(config.system_prompt.is_none());
        // This is the expected behavior - no panic, no error
        // Daemon would read from preset, but if file is missing or role has no
        // system_prompt_file, system_prompt stays None
    }

    // --- WorkerSpec tests with agents ---

    #[test]
    fn worker_spec_backward_compat() {
        // Old usage: from_program without agents/creator_id
        let spec = WorkerSpec::from_program("nexus42");
        assert_eq!(spec.program, "nexus42");
        assert!(spec.args.is_empty());
        assert!(spec.creator_id.is_empty());
        assert!(spec.agents.is_empty());
    }

    #[test]
    fn worker_spec_with_agents() {
        let agents = vec![
            WorkerAgentConfig::new("s1".to_string(), "claude-acp".to_string())
                .with_role("writer".to_string()),
            WorkerAgentConfig::new("s2".to_string(), "codex-acp".to_string())
                .with_role("reviewer".to_string()),
        ];

        let spec = WorkerSpec::from_program("nexus42")
            .with_creator_id("creator-42")
            .with_agents(agents);

        assert_eq!(spec.creator_id, "creator-42");
        assert_eq!(spec.agents.len(), 2);
    }

    #[test]
    fn worker_spec_build_agent_ref_args() {
        let agents = vec![
            WorkerAgentConfig::new("s1".to_string(), "claude-acp".to_string())
                .with_role("writer".to_string())
                .with_model("claude-sonnet-4".to_string()),
            WorkerAgentConfig::new("s2".to_string(), "codex-acp".to_string())
                .with_role("reviewer".to_string()),
        ];

        let spec = WorkerSpec::from_program("nexus42").with_agents(agents);

        let args = spec.build_agent_ref_args();
        assert_eq!(args.len(), 2);
        assert_eq!(args[0], "writer:claude-acp:claude-sonnet-4");
        assert_eq!(args[1], "reviewer:codex-acp");
    }

    #[test]
    fn worker_spec_build_agent_ref_args_empty() {
        let spec = WorkerSpec::from_program("nexus42");
        let args = spec.build_agent_ref_args();
        assert!(args.is_empty());
    }

    #[test]
    fn worker_spec_default() {
        let spec = WorkerSpec::default();
        assert!(spec.program.is_empty());
        assert!(spec.creator_id.is_empty());
        assert!(spec.agents.is_empty());
    }

    #[test]
    fn worker_spec_builder_chain() {
        let spec = WorkerSpec::from_program("nexus42")
            .with_arg("--creator")
            .with_arg("test-creator")
            .with_env("RUST_LOG", "debug")
            .with_working_dir("/tmp")
            .with_creator_id("creator-123")
            .with_agent(WorkerAgentConfig::new(
                "s1".to_string(),
                "claude-acp".to_string(),
            ));

        assert_eq!(spec.args.len(), 2);
        assert_eq!(spec.env.len(), 1);
        assert_eq!(spec.working_dir, Some("/tmp".to_string()));
        assert_eq!(spec.creator_id, "creator-123");
        assert_eq!(spec.agents.len(), 1);
    }

    // --- AgentSessionSummary tests ---

    #[test]
    fn session_summary_is_ready() {
        let summary = AgentSessionSummary {
            session_id: "s1".to_string(),
            acp_agent_id: "claude-acp".to_string(),
            role: Some("writer".to_string()),
            model: Some("claude-sonnet-4".to_string()),
            state: "ready".to_string(),
            uptime_ms: 1000,
        };
        assert!(summary.is_ready());
        assert!(!summary.is_error());
    }

    #[test]
    fn session_summary_is_error() {
        let summary = AgentSessionSummary {
            session_id: "s1".to_string(),
            acp_agent_id: "claude-acp".to_string(),
            role: None,
            model: None,
            state: "error".to_string(),
            uptime_ms: 1000,
        };
        assert!(!summary.is_ready());
        assert!(summary.is_error());
    }

    #[test]
    fn session_summary_serialization() {
        let summary = AgentSessionSummary {
            session_id: "s1".to_string(),
            acp_agent_id: "claude-acp".to_string(),
            role: Some("writer".to_string()),
            model: None,
            state: "ready".to_string(),
            uptime_ms: 5000,
        };

        let json = serde_json::to_string(&summary).expect("serialize");
        assert!(json.contains("s1"));
        assert!(json.contains("claude-acp"));
        assert!(json.contains("ready"));

        let parsed: AgentSessionSummary = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(parsed.session_id, summary.session_id);
        assert_eq!(parsed.state, summary.state);
    }

    // --- WorkerHandle from_ipc_for_test ---

    #[tokio::test]
    async fn worker_handle_from_ipc_for_test() {
        use crate::worker::{DuplexTransport, IpcClient};

        let (daemon, _worker) = DuplexTransport::new_pair();
        let ipc = IpcClient::new(Box::new(daemon));
        let handle = WorkerHandle::from_ipc_for_test(ipc);

        assert_eq!(handle.pid(), 0); // Mock PID
        assert!(!handle.ipc_client().is_closed());
        // CancellationToken can be cloned and checked for cancellation status.
        let cancel = handle.cancel_token();
        assert!(!cancel.is_cancelled());
    }
}
