//! `nexus42 preset init|list|validate` — manage user-installed presets.
//!
//! Init: scaffolds a new preset directory under `~/.nexus42/presets/<name>/`.
//! List: enumerates all available presets grouped by source.
//! Validate: checks a preset YAML file for structural validity.
//!
//! `preset list` works offline — embedded preset IDs come from compile-time
//! data generated by build.rs, system/user presets are scanned from the
//! filesystem. No daemon connection required.

#![allow(clippy::print_literal)]

use crate::config::{nexus_home, CliConfig};
use crate::errors::{CliError, Result};
use clap::{Parser, Subcommand};
use nexus_home_layout::user_preset_bundle_dir;

// Compile-time generated embedded preset IDs (from build.rs).
include!(concat!(env!("OUT_DIR"), "/embedded_preset_ids.rs"));

/// The template YAML for a new user preset.
const PRESET_INIT_TEMPLATE: &str = r#"preset:
  id: {{name}}
  version: 1
  kind: creator
  description: "Custom orchestration strategy"
  requires_capabilities: []
  initial: start
  terminal: done
states:
  - id: start
    description: "Begin the workflow"
    enter:
      - kind: capability
        name: workspace.open
        args:
          prompt_file: prompts/start.md
          vars:
            input: "{{preset.input}}"
    exit_when:
      kind: manual
    next: done
  - id: done
    terminal: true
"#;

/// Template for the default prompt file scaffolding.
const PROMPT_INIT_CONTENT: &str = r"# Start Prompt

{{input}}
";

#[derive(Debug, Subcommand)]
pub enum PresetCommand {
    /// Create a new user preset bundle
    Init {
        /// Preset name (used as directory name and preset ID)
        name: String,
    },
    /// List all available presets grouped by source
    List,
    /// Validate a preset YAML file for structural correctness
    Validate {
        /// Path to the preset.yaml file to validate
        path: String,
    },
    /// Reload a preset from disk (re-read preset.yaml)
    Reload {
        /// Preset ID to reload
        preset_id: String,
    },
}

#[derive(Debug, Parser)]
#[command(subcommand_required = true, name = "preset")]
struct PresetCli {
    #[command(subcommand)]
    command: PresetCommand,
}

/// Run the preset command.
///
/// # Errors
///
/// Returns an error if:
/// - Nexus home directory cannot be resolved
/// - Preset name validation fails
/// - File I/O operations fail
/// - Daemon API calls fail and fallback also fails
pub async fn run(cmd: PresetCommand, config: &CliConfig) -> Result<()> {
    match cmd {
        PresetCommand::Init { name } => {
            let home = nexus_home()?;

            // Try daemon API first (T38: migration)
            let client = crate::api::DaemonClient::from_config(config);
            if client.health_check().await? {
                let req = crate::api::models::ScaffoldPresetRequest { name: name.clone() };
                match client.scaffold_preset(&req).await {
                    Ok(resp) => {
                        println!("✓ Created preset '{}' at {}", resp.id, resp.path);
                        println!("  preset.yaml  — manifest (edit to define your strategy)");
                        println!("  prompts/     — prompt templates");
                        println!();
                        println!(
                            "Next: edit {}/preset.yaml to customize your strategy.",
                            resp.path
                        );
                        return Ok(());
                    }
                    Err(e) => {
                        eprintln!("nexus42: daemon preset init failed, falling back: {e}");
                    }
                }
            }

            // Fallback: direct FS scaffold
            init_preset_at(&home, &name)
        }
        PresetCommand::List => {
            // Try daemon API first (T38: migration)
            let client = crate::api::DaemonClient::from_config(config);
            if client.health_check().await? {
                match client.list_presets().await {
                    Ok(resp) => {
                        list_presets_from_daemon(&resp);
                        return Ok(());
                    }
                    Err(e) => {
                        eprintln!("nexus42: daemon preset list failed, falling back: {e}");
                    }
                }
            }

            // Fallback: offline list
            let home = crate::config::user_home_dir()?;
            list_presets_offline(&home);
            Ok(())
        }
        PresetCommand::Validate { path } => {
            // Try daemon API first (T38: migration)
            let client = crate::api::DaemonClient::from_config(config);
            if client.health_check().await? {
                let req = crate::api::models::ValidatePresetRequest { path: path.clone() };
                match client.validate_preset(&req).await {
                    Ok(resp) => {
                        if resp.valid {
                            println!("✓ Preset is valid");
                            if let Some(id) = &resp.id {
                                println!("  ID: {id}");
                            }
                            if let Some(ver) = resp.version {
                                println!("  Version: {ver}");
                            }
                            if let Some(count) = resp.state_count {
                                println!("  States: {count}");
                            }
                        } else {
                            println!("✗ Preset validation failed:");
                            for err in &resp.errors {
                                println!("  - {err}");
                            }
                            return Err(CliError::Other("Preset validation failed".to_string()));
                        }
                        return Ok(());
                    }
                    Err(e) => {
                        eprintln!("nexus42: daemon preset validate failed, falling back: {e}");
                    }
                }
            }

            // Fallback: local validation
            validate_preset(&path)
        }
        PresetCommand::Reload { preset_id } => {
            // Try daemon API first (T38: migration)
            let client = crate::api::DaemonClient::from_config(config);
            if client.health_check().await? {
                match client.reload_preset(&preset_id).await {
                    Ok(resp) => {
                        println!("✓ Preset '{}' reloaded: {}", resp.id, resp.reloaded);
                        return Ok(());
                    }
                    Err(e) => {
                        eprintln!("nexus42: daemon preset reload failed: {e}");
                        return Err(e);
                    }
                }
            }

            Err(CliError::Other(
                "Preset reload requires a running daemon. Start with `nexus42 daemon start`."
                    .to_string(),
            ))
        }
    }
}

/// Print presets grouped by source from daemon response.
fn list_presets_from_daemon(resp: &crate::api::models::ListPresetsGroupedResponse) {
    println!("Available presets:\n");

    // Embedded section
    println!("[embedded]");
    if resp.embedded.is_empty() {
        println!("  (none)");
    } else {
        for p in &resp.embedded {
            let user_override = resp.user.iter().any(|u| u.id == p.id);
            if user_override {
                println!("  {}  (overridden by user preset)", p.id);
            } else {
                println!("  {}", p.id);
            }
        }
    }

    // System section
    println!("\n[system]");
    if resp.system.is_empty() {
        println!("  (none)");
    } else {
        for p in &resp.system {
            println!("  {}", p.id);
        }
    }

    // User section
    println!("\n[user]");
    if resp.user.is_empty() {
        println!("  (none)");
    } else {
        for p in &resp.user {
            let embedded_override = resp.embedded.iter().any(|e| e.id == p.id);
            if embedded_override {
                println!("  {}  (overrides embedded)", p.id);
            } else {
                println!("  {}", p.id);
            }
        }
    }

    let total = resp.embedded.len() + resp.system.len() + resp.user.len();
    println!(
        "\n{} preset(s) total ({} embedded, {} system, {} user)",
        total,
        resp.embedded.len(),
        resp.system.len(),
        resp.user.len()
    );
}

/// Internal: scaffold a preset at a specific nexus home path.
fn init_preset_at(home: &std::path::Path, name: &str) -> Result<()> {
    // Validate name is a single path segment.
    if name.is_empty()
        || name.contains('/')
        || name.contains('\\')
        || name == "."
        || name == ".."
        || name == "_system"
    {
        return Err(CliError::Other(format!(
            "Invalid preset name {name:?}. Must be a non-empty path segment without path separators, \
              not '.', '..', and must not be the reserved name '_system'."
        )));
    }

    let bundle_dir = user_preset_bundle_dir(home, name);

    if bundle_dir.exists() {
        return Err(CliError::Other(format!(
            "Preset '{name}' already exists at {}",
            bundle_dir.display()
        )));
    }

    // Create directory structure.
    let prompts_dir = bundle_dir.join("prompts");
    std::fs::create_dir_all(&prompts_dir)?;

    // Write preset.yaml with the name substituted in.
    let preset_yaml = PRESET_INIT_TEMPLATE.replace("{{name}}", name);
    std::fs::write(bundle_dir.join("preset.yaml"), preset_yaml)?;

    // Write a default start prompt.
    std::fs::write(prompts_dir.join("start.md"), PROMPT_INIT_CONTENT)?;

    println!("✓ Created preset '{}' at {}", name, bundle_dir.display());
    println!("  preset.yaml  — manifest (edit to define your strategy)");
    println!("  prompts/     — prompt templates");
    println!();
    println!(
        "Next: edit {} to customize your strategy.",
        bundle_dir.join("preset.yaml").display()
    );

    Ok(())
}

/// List all available presets grouped by source.
///
/// Groups presets into `[embedded]`, `[system]`, and `[user]` sections.
/// If a user preset has the same ID as an embedded preset, the user version
/// takes precedence and is marked with `(overrides embedded)`.
///
/// Works offline — embedded preset IDs come from compile-time data,
/// system/user presets are scanned from the filesystem.
fn list_presets_offline(home: &std::path::Path) {
    // ── Embedded presets ────────────────────────────────────────────
    // Compile-time list from build.rs scanning embedded-presets/ dir.
    let embedded: Vec<&str> = EMBEDDED_PRESET_IDS.to_vec();

    // ── System presets ──────────────────────────────────────────────
    // Scan _system/ subdirectories directly from the filesystem.
    let system_dir = nexus_home_layout::user_preset_base_dir(home).join("_system");
    let mut system_ids: Vec<String> = Vec::new();
    if system_dir.exists() {
        if let Ok(entries) = std::fs::read_dir(&system_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir()
                    && path.join("preset.yaml").exists()
                    && !path
                        .file_name()
                        .and_then(|n| n.to_str())
                        .is_some_and(|n| n.starts_with('.'))
                {
                    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                        system_ids.push(format!("_system.{name}"));
                    }
                }
            }
        }
        system_ids.sort();
    }

    // ── User presets ────────────────────────────────────────────────
    let user_ids = nexus_home_layout::list_user_preset_ids(home);

    // Scan for underscore-prefixed user presets (warn instead of silently skip).
    let mut underscore_ids: Vec<String> = Vec::new();
    let user_base = nexus_home_layout::user_preset_base_dir(home);
    if user_base.exists() {
        if let Ok(entries) = std::fs::read_dir(&user_base) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                        if name.starts_with('_')
                            && name != "_system"
                            && path.join("preset.yaml").exists()
                        {
                            underscore_ids.push(name.to_string());
                        }
                    }
                }
            }
        }
        underscore_ids.sort();
    }

    println!("Available presets:\n");

    // Embedded section.
    println!("[embedded]");
    if embedded.is_empty() {
        println!("  (none)");
    } else {
        for id in &embedded {
            let user_override = user_ids.iter().any(|e| e == *id);
            if user_override {
                println!("  {id}  (overridden by user preset)");
            } else {
                println!("  {id}");
            }
        }
    }

    // System section.
    println!("\n[system]");
    if system_ids.is_empty() {
        println!("  (none)");
    } else {
        for id in &system_ids {
            println!("  {id}");
        }
    }

    // User section.
    println!("\n[user]");
    if user_ids.is_empty() {
        println!("  (none)");
    } else {
        for id in &user_ids {
            let embedded_override = embedded.iter().any(|e| *e == id);
            if embedded_override {
                println!("  {id}  (overrides embedded)");
            } else {
                println!("  {id}");
            }
        }
    }

    // Warnings for underscore-prefixed presets.
    if !underscore_ids.is_empty() {
        eprintln!(
            "\n⚠ Warning: the following user presets start with '_' and are skipped during preset resolution:"
        );
        for id in &underscore_ids {
            eprintln!("  {id}");
        }
        eprintln!("  Rename them to remove the '_' prefix if they should be active.");
    }

    println!(
        "\n{} preset(s) total ({} embedded, {} system, {} user)",
        embedded.len() + system_ids.len() + user_ids.len(),
        embedded.len(),
        system_ids.len(),
        user_ids.len()
    );
}

// ---------------------------------------------------------------------------
// Validate subcommand
// ---------------------------------------------------------------------------

/// Default maximum YAML file size for validation (1 MiB).
const VALIDATE_MAX_YAML_SIZE: usize = 1024 * 1024;

/// Default maximum YAML nesting depth for validation.
const VALIDATE_MAX_YAML_DEPTH: usize = 10;

/// Validate a preset YAML file for structural correctness.
///
/// Checks:
/// - YAML is valid and parseable
/// - File size does not exceed the default limit (1 MiB)
/// - Nesting depth does not exceed the default limit (10)
/// - Required top-level fields are present (`preset`, `states`)
/// - Manifest deserializes correctly via `PresetManifest`
fn validate_preset(path: &str) -> Result<()> {
    let file_path = std::path::Path::new(path);

    if !file_path.exists() {
        return Err(CliError::Other(format!(
            "File not found: {}",
            file_path.display()
        )));
    }

    // Check file size via metadata BEFORE reading to prevent OOM on large
    // files (QC3 W-001 — unbounded allocation).
    let metadata = std::fs::metadata(file_path)
        .map_err(|e| CliError::Other(format!("Failed to stat {}: {e}", file_path.display())))?;
    if metadata.len() > VALIDATE_MAX_YAML_SIZE as u64 {
        return Err(CliError::Other(format!(
            "Preset YAML exceeds maximum size ({} bytes, limit is {} bytes). \
                Simplify the preset or split into smaller presets.",
            metadata.len(),
            VALIDATE_MAX_YAML_SIZE
        )));
    }

    let yaml = std::fs::read_to_string(file_path)
        .map_err(|e| CliError::Other(format!("Failed to read {}: {e}", file_path.display())))?;

    // Size check (defense-in-depth: metadata size may differ slightly from
    // string byte length on some platforms).
    if yaml.len() > VALIDATE_MAX_YAML_SIZE {
        return Err(CliError::Other(format!(
            "Preset YAML exceeds maximum size ({} bytes, limit is {} bytes). \
                Simplify the preset or split into smaller presets.",
            yaml.len(),
            VALIDATE_MAX_YAML_SIZE
        )));
    }

    // Parse to generic Value for depth measurement.
    let yaml_value: serde_yaml::Value = serde_yaml::from_str(&yaml)
        .map_err(|e| CliError::Other(format!("YAML parse error: {e}")))?;

    // Depth check — uses the canonical implementation from nexus-orchestration
    // (QC1 W-A01 — single truth source for depth semantics).
    let actual_depth = nexus_orchestration::preset::yaml_value_depth(&yaml_value);
    if actual_depth > VALIDATE_MAX_YAML_DEPTH {
        return Err(CliError::Other(format!(
            "Preset YAML nesting depth ({actual_depth}) exceeds maximum ({VALIDATE_MAX_YAML_DEPTH}). \
                Flatten deeply nested structures in your preset."
        )));
    }

    // Deserialize from the already-parsed Value (avoids double-parse that
    // widens the stack-overflow attack surface — QC3 W-002).
    let manifest: nexus_contracts::local::orchestration::preset::PresetManifest =
        serde_yaml::from_value(yaml_value)
            .map_err(|e| CliError::Other(format!("Structural validation error: {e}")))?;

    // Basic structural checks.
    if manifest.preset.id.is_empty() {
        return Err(CliError::Other("preset.id must not be empty".to_string()));
    }

    if manifest.states.is_empty() {
        return Err(CliError::Other(
            "preset must have at least one state".to_string(),
        ));
    }

    // Check initial and terminal reference valid states.
    let state_ids: std::collections::HashSet<&str> =
        manifest.states.iter().map(|s| s.id.as_str()).collect();

    if !state_ids.contains(manifest.preset.initial.as_str()) {
        return Err(CliError::Other(format!(
            "preset.initial '{}' does not reference a valid state",
            manifest.preset.initial
        )));
    }

    if !state_ids.contains(manifest.preset.terminal.as_str()) {
        return Err(CliError::Other(format!(
            "preset.terminal '{}' does not reference a valid state",
            manifest.preset.terminal
        )));
    }

    println!("✓ Preset is valid");
    println!("  ID: {}", manifest.preset.id);
    println!("  Version: {}", manifest.preset.version);
    println!("  States: {}", manifest.states.len());
    if let Some(ref inner_graphs) = manifest.inner_graphs {
        if !inner_graphs.is_empty() {
            println!(
                "  Inner graphs: {}",
                inner_graphs
                    .keys()
                    .map(String::as_str)
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preset_init_parses() {
        let cmd = PresetCli::try_parse_from(["preset", "init", "my-strategy"]).expect("parse");
        match cmd.command {
            PresetCommand::Init { name } => assert_eq!(name, "my-strategy"),
            _ => panic!("expected Init variant"),
        }
    }

    #[test]
    fn preset_list_parses() {
        let cmd = PresetCli::try_parse_from(["preset", "list"]).expect("parse");
        match cmd.command {
            PresetCommand::List => {} // expected
            _ => panic!("expected List variant"),
        }
    }

    #[test]
    fn preset_subcommand_required() {
        let result = PresetCli::try_parse_from(["preset"]);
        assert!(result.is_err());
    }

    #[test]
    fn init_preset_creates_directory_structure() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let nexus_home = tmp.path();

        let result = init_preset_at(nexus_home, "test-strat");
        assert!(result.is_ok(), "init should succeed: {result:?}");

        let bundle_dir = user_preset_bundle_dir(nexus_home, "test-strat");
        assert!(bundle_dir.join("preset.yaml").exists());
        assert!(bundle_dir.join("prompts").exists());
        assert!(bundle_dir.join("prompts/start.md").exists());

        // Verify preset.yaml content includes the name.
        let content =
            std::fs::read_to_string(bundle_dir.join("preset.yaml")).expect("read preset.yaml");
        assert!(content.contains("id: test-strat"));
    }

    #[test]
    fn init_preset_errors_on_existing() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let nexus_home = tmp.path();

        // First init should succeed.
        init_preset_at(nexus_home, "existing-strat").expect("first init");

        // Second init should fail.
        let err =
            init_preset_at(nexus_home, "existing-strat").expect_err("second init should fail");
        let display = format!("{err}");
        assert!(
            display.contains("already exists"),
            "expected 'already exists' error: {display}"
        );
    }

    #[test]
    fn init_preset_rejects_invalid_names() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let nexus_home = tmp.path();

        let empty = init_preset_at(nexus_home, "");
        assert!(empty.is_err());

        let slash = init_preset_at(nexus_home, "foo/bar");
        assert!(slash.is_err());

        let dot = init_preset_at(nexus_home, ".");
        assert!(dot.is_err());

        let dotdot = init_preset_at(nexus_home, "..");
        assert!(dotdot.is_err());

        let system_prefix = init_preset_at(nexus_home, "_system");
        assert!(system_prefix.is_err());
    }

    #[test]
    fn init_preset_accepts_underscore_prefix() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let nexus_home = tmp.path();

        // Non-reserved underscore-prefixed names should be accepted.
        let result = init_preset_at(nexus_home, "_draft");
        assert!(result.is_ok(), "_draft should be accepted: {result:?}");

        let bundle_dir = user_preset_bundle_dir(nexus_home, "_draft");
        assert!(bundle_dir.join("preset.yaml").exists());
    }

    #[test]
    fn preset_validate_parses() {
        let cmd = PresetCli::try_parse_from(["preset", "validate", "path/to/preset.yaml"])
            .expect("parse");
        match cmd.command {
            PresetCommand::Validate { path } => assert_eq!(path, "path/to/preset.yaml"),
            _ => panic!("expected Validate variant"),
        }
    }

    #[test]
    fn preset_reload_parses() {
        let cmd = PresetCli::try_parse_from(["preset", "reload", "my-strategy"]).expect("parse");
        match cmd.command {
            PresetCommand::Reload { preset_id } => assert_eq!(preset_id, "my-strategy"),
            _ => panic!("expected Reload variant"),
        }
    }

    #[test]
    fn validate_accepts_valid_preset() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let yaml_path = tmp.path().join("preset.yaml");
        std::fs::write(
            &yaml_path,
            "
preset:
  id: validate-test
  version: 1
  kind: creator
  description: test
  requires_capabilities: []
  initial: a
  terminal: b
states:
  - id: a
    enter: []
    exit_when: { kind: manual }
    next: b
  - id: b
    terminal: true
",
        )
        .expect("write yaml");

        let result = validate_preset(yaml_path.to_str().expect("valid utf-8 path"));
        assert!(result.is_ok(), "valid preset should pass: {result:?}");
    }

    #[test]
    fn validate_rejects_invalid_yaml() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let yaml_path = tmp.path().join("preset.yaml");
        std::fs::write(&yaml_path, "not: valid: yaml: [").expect("write yaml");

        let result = validate_preset(yaml_path.to_str().expect("valid utf-8 path"));
        assert!(result.is_err());
        let msg = format!("{result:?}");
        assert!(
            msg.contains("YAML parse error"),
            "expected YAML parse error: {msg}"
        );
    }

    #[test]
    fn validate_rejects_nonexistent_file() {
        let result = validate_preset("/nonexistent/path/preset.yaml");
        assert!(result.is_err());
        let msg = format!("{result:?}");
        assert!(
            msg.contains("File not found"),
            "expected file not found: {msg}"
        );
    }

    #[test]
    fn list_user_preset_ids_finds_dirs_with_preset_yaml() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let base = nexus_home_layout::user_preset_base_dir(home);
        std::fs::create_dir_all(&base).expect("create base dir");

        // Create a valid preset dir.
        std::fs::create_dir_all(base.join("valid-strat")).expect("create valid-strat");
        std::fs::write(base.join("valid-strat/preset.yaml"), "dummy").expect("write preset.yaml");

        // Create a dir without preset.yaml (should be skipped).
        std::fs::create_dir_all(base.join("empty-dir")).expect("create empty-dir");

        let result = nexus_home_layout::list_user_preset_ids(home);
        assert_eq!(result.len(), 1);
        assert_eq!(result[0], "valid-strat");
    }
}
