//! `nexus42 preset init|list` — manage user-installed presets.
//!
//! Init: scaffolds a new preset directory under `~/.nexus42/presets/<name>/`.
//! List: enumerates all available presets grouped by source.
//!
//! `preset list` works offline — embedded preset IDs come from compile-time
//! data generated by build.rs, system/user presets are scanned from the
//! filesystem. No daemon connection required.

#![allow(clippy::print_literal)]

use crate::config::{nexus_home, CliConfig};
use crate::errors::{CliError, Result};
use clap::{Parser, Subcommand};
use nexus_home_layout::user_preset_bundle_dir;

// Compile-time generated embedded preset IDs (from build.rs).
include!(concat!(env!("OUT_DIR"), "/embedded_preset_ids.rs"));

/// The template YAML for a new user preset.
const PRESET_INIT_TEMPLATE: &str = r#"preset:
  id: {{name}}
  version: 1
  kind: creator
  description: "Custom orchestration strategy"
  requires_capabilities: []
  initial: start
  terminal: done
states:
  - id: start
    description: "Begin the workflow"
    enter:
      - kind: capability
        name: workspace.open
        args:
          prompt_file: prompts/start.md
          vars:
            input: "{{preset.input}}"
    exit_when:
      kind: manual
    next: done
  - id: done
    terminal: true
"#;

/// Template for the default prompt file scaffolding.
const PROMPT_INIT_CONTENT: &str = r"# Start Prompt

{{input}}
";

#[derive(Debug, Subcommand)]
pub enum PresetCommand {
    /// Create a new user preset bundle
    Init {
        /// Preset name (used as directory name and preset ID)
        name: String,
    },
    /// List all available presets grouped by source
    List,
}

#[derive(Debug, Parser)]
#[command(subcommand_required = true, name = "preset")]
struct PresetCli {
    #[command(subcommand)]
    command: PresetCommand,
}

/// Run the preset command.
///
/// # Errors
///
/// Returns an error if:
/// - Nexus home directory cannot be resolved
/// - Preset name validation fails
/// - File I/O operations fail
pub fn run(cmd: PresetCommand, _config: &CliConfig) -> Result<()> {
    match cmd {
        PresetCommand::Init { name } => {
            let home = nexus_home()?;
            init_preset_at(&home, &name)
        }
        PresetCommand::List => {
            let home = crate::config::user_home_dir()?;
            list_presets_offline(&home);
            Ok(())
        }
    }
}

/// Internal: scaffold a preset at a specific nexus home path.
fn init_preset_at(home: &std::path::Path, name: &str) -> Result<()> {
    // Validate name is a single path segment.
    if name.is_empty()
        || name.contains('/')
        || name.contains('\\')
        || name == "."
        || name == ".."
        || name.starts_with('_')
    {
        return Err(CliError::Other(format!(
            "Invalid preset name {name:?}. Must be a non-empty path segment without path separators, \
             not '.', '..', and must not start with '_'."
        )));
    }

    let bundle_dir = user_preset_bundle_dir(home, name);

    if bundle_dir.exists() {
        return Err(CliError::Other(format!(
            "Preset '{name}' already exists at {}",
            bundle_dir.display()
        )));
    }

    // Create directory structure.
    let prompts_dir = bundle_dir.join("prompts");
    std::fs::create_dir_all(&prompts_dir)?;

    // Write preset.yaml with the name substituted in.
    let preset_yaml = PRESET_INIT_TEMPLATE.replace("{{name}}", name);
    std::fs::write(bundle_dir.join("preset.yaml"), preset_yaml)?;

    // Write a default start prompt.
    std::fs::write(prompts_dir.join("start.md"), PROMPT_INIT_CONTENT)?;

    println!("✓ Created preset '{}' at {}", name, bundle_dir.display());
    println!("  preset.yaml  — manifest (edit to define your strategy)");
    println!("  prompts/     — prompt templates");
    println!();
    println!(
        "Next: edit {} to customize your strategy.",
        bundle_dir.join("preset.yaml").display()
    );

    Ok(())
}

/// List all available presets grouped by source.
///
/// Groups presets into `[embedded]`, `[system]`, and `[user]` sections.
/// If a user preset has the same ID as an embedded preset, the user version
/// takes precedence and is marked with `(overrides embedded)`.
///
/// Works offline — embedded preset IDs come from compile-time data,
/// system/user presets are scanned from the filesystem.
fn list_presets_offline(home: &std::path::Path) {
    // ── Embedded presets ────────────────────────────────────────────
    // Compile-time list from build.rs scanning embedded-presets/ dir.
    let embedded: Vec<&str> = EMBEDDED_PRESET_IDS.to_vec();

    // ── System presets ──────────────────────────────────────────────
    // Scan _system/ subdirectories directly from the filesystem.
    let system_dir = nexus_home_layout::user_preset_base_dir(home).join("_system");
    let mut system_ids: Vec<String> = Vec::new();
    if system_dir.exists() {
        if let Ok(entries) = std::fs::read_dir(&system_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir()
                    && path.join("preset.yaml").exists()
                    && !path
                        .file_name()
                        .and_then(|n| n.to_str())
                        .is_some_and(|n| n.starts_with('.'))
                {
                    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                        system_ids.push(format!("_system.{name}"));
                    }
                }
            }
        }
        system_ids.sort();
    }

    // ── User presets ────────────────────────────────────────────────
    let user_ids = nexus_home_layout::list_user_preset_ids(home);

    println!("Available presets:\n");

    // Embedded section.
    println!("[embedded]");
    if embedded.is_empty() {
        println!("  (none)");
    } else {
        for id in &embedded {
            let user_override = user_ids.iter().any(|e| e == *id);
            if user_override {
                println!("  {id}  (overridden by user preset)");
            } else {
                println!("  {id}");
            }
        }
    }

    // System section.
    println!("\n[system]");
    if system_ids.is_empty() {
        println!("  (none)");
    } else {
        for id in &system_ids {
            println!("  {id}");
        }
    }

    // User section.
    println!("\n[user]");
    if user_ids.is_empty() {
        println!("  (none)");
    } else {
        for id in &user_ids {
            let embedded_override = embedded.iter().any(|e| *e == id);
            if embedded_override {
                println!("  {id}  (overrides embedded)");
            } else {
                println!("  {id}");
            }
        }
    }

    println!(
        "\n{} preset(s) total ({} embedded, {} system, {} user)",
        embedded.len() + system_ids.len() + user_ids.len(),
        embedded.len(),
        system_ids.len(),
        user_ids.len()
    );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preset_init_parses() {
        let cmd = PresetCli::try_parse_from(["preset", "init", "my-strategy"]).expect("parse");
        match cmd.command {
            PresetCommand::Init { name } => assert_eq!(name, "my-strategy"),
            PresetCommand::List => panic!("expected Init variant"),
        }
    }

    #[test]
    fn preset_list_parses() {
        let cmd = PresetCli::try_parse_from(["preset", "list"]).expect("parse");
        match cmd.command {
            PresetCommand::List => {} // expected
            PresetCommand::Init { .. } => panic!("expected List variant"),
        }
    }

    #[test]
    fn preset_subcommand_required() {
        let result = PresetCli::try_parse_from(["preset"]);
        assert!(result.is_err());
    }

    #[test]
    fn init_preset_creates_directory_structure() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let nexus_home = tmp.path();

        let result = init_preset_at(nexus_home, "test-strat");
        assert!(result.is_ok(), "init should succeed: {result:?}");

        let bundle_dir = user_preset_bundle_dir(nexus_home, "test-strat");
        assert!(bundle_dir.join("preset.yaml").exists());
        assert!(bundle_dir.join("prompts").exists());
        assert!(bundle_dir.join("prompts/start.md").exists());

        // Verify preset.yaml content includes the name.
        let content =
            std::fs::read_to_string(bundle_dir.join("preset.yaml")).expect("read preset.yaml");
        assert!(content.contains("id: test-strat"));
    }

    #[test]
    fn init_preset_errors_on_existing() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let nexus_home = tmp.path();

        // First init should succeed.
        init_preset_at(nexus_home, "existing-strat").expect("first init");

        // Second init should fail.
        let err =
            init_preset_at(nexus_home, "existing-strat").expect_err("second init should fail");
        let display = format!("{err}");
        assert!(
            display.contains("already exists"),
            "expected 'already exists' error: {display}"
        );
    }

    #[test]
    fn init_preset_rejects_invalid_names() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let nexus_home = tmp.path();

        let empty = init_preset_at(nexus_home, "");
        assert!(empty.is_err());

        let slash = init_preset_at(nexus_home, "foo/bar");
        assert!(slash.is_err());

        let dot = init_preset_at(nexus_home, ".");
        assert!(dot.is_err());

        let dotdot = init_preset_at(nexus_home, "..");
        assert!(dotdot.is_err());

        let system_prefix = init_preset_at(nexus_home, "_system");
        assert!(system_prefix.is_err());
    }

    #[test]
    fn list_user_preset_ids_finds_dirs_with_preset_yaml() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let base = nexus_home_layout::user_preset_base_dir(home);
        std::fs::create_dir_all(&base).expect("create base dir");

        // Create a valid preset dir.
        std::fs::create_dir_all(base.join("valid-strat")).expect("create valid-strat");
        std::fs::write(base.join("valid-strat/preset.yaml"), "dummy").expect("write preset.yaml");

        // Create a dir without preset.yaml (should be skipped).
        std::fs::create_dir_all(base.join("empty-dir")).expect("create empty-dir");

        let result = nexus_home_layout::list_user_preset_ids(home);
        assert_eq!(result.len(), 1);
        assert_eq!(result[0], "valid-strat");
    }
}
