//! AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY
//! Source: core/provider-host-event.schema.json
//! Generated by: pnpm run codegen (hand-written emitter for externally-tagged union)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProviderHostEventStatusLevel {
    Info,
    Warning,
    Error,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProviderHostEventFinishReason {
    EndTurn,
    MaxTokens,
    MaxTurnRequests,
    Refusal,
    Cancelled,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProviderHostEventSessionStopReason {
    GracefulShutdown,
    ProviderExit,
    Error,
    Cancelled,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProviderHostEvent {
    SessionCreated(ProviderHostEventSessionCreated),
    OpStarted(ProviderHostEventOpStarted),
    ThoughtDelta(ProviderHostEventTextDelta),
    MessageDelta(ProviderHostEventTextDelta),
    ToolCall(ProviderHostEventToolCall),
    ToolCallUpdate(ProviderHostEventToolCallUpdate),
    PlanUpdate(ProviderHostEventPlanUpdate),
    Status(ProviderHostEventStatus),
    OpFinished(ProviderHostEventOpFinished),
    OpFailed(ProviderHostEventOpFailed),
    SessionStopped(ProviderHostEventSessionStopped),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventSessionCreated {
    pub session_id: String,
    pub provider_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventOpStarted {
    pub session_id: String,
    pub op_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventTextDelta {
    pub session_id: String,
    pub op_id: String,
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventToolCall {
    pub session_id: String,
    pub op_id: String,
    pub tool_call_id: String,
    pub tool_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventToolCallUpdate {
    pub session_id: String,
    pub op_id: String,
    pub tool_call_id: String,
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventPlanUpdate {
    pub session_id: String,
    pub op_id: String,
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventStatus {
    pub session_id: Option<String>,
    pub level: ProviderHostEventStatusLevel,
    pub message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventOpFinished {
    pub session_id: String,
    pub op_id: String,
    pub reason: ProviderHostEventFinishReason,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventOpFailed {
    pub session_id: String,
    pub op_id: String,
    pub error_category: String,
    pub error_message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHostEventSessionStopped {
    pub session_id: String,
    pub reason: ProviderHostEventSessionStopReason,
}
